#!/usr/bin/env python3
"""
PVL Build Worker — Downloads from Google Drive, processes ZIP, uploads to Hugging Face.

Runs on GitHub Actions. Reads all config from environment variables.
Posts real-time progress updates back to WordPress.

Environment variables (set by GitHub Actions):
  SA_CREDENTIALS_PATH   — Path to Service Account JSON
  GAS_BRIDGE_URL        — Google Apps Script bridge URL
  GAS_BRIDGE_SECRET     — GAS bridge shared secret
  HF_TOKEN              — Hugging Face write token
  HF_REPO_ID            — HF dataset repo (e.g. adminlexzytech/phone-firmware)
  BUILD_CALLBACK_SECRET — Shared secret for progress updates
  FILE_ID               — Google Drive file ID to download
  FILE_NAME             — Original filename
  CALLBACK_URL          — WordPress AJAX URL for progress reports
  BUILD_ID              — Unique build identifier
  EXCLUDE_PATTERNS      — Newline-separated glob patterns to exclude
"""

import os
import sys
import json
import time
import threading
import shutil
import hashlib
import zipfile
import fnmatch
import tempfile
import traceback
import subprocess
import urllib.parse
from pathlib import Path
from datetime import datetime, timezone

import jwt       # PyJWT
import requests
from huggingface_hub import HfApi

from mega_url import is_mega_url
from mega_download import mega_download
from source_labels import source_label
import dedup_client
import name_composer
import payload_reader
import zip_passthrough

# ─────────────────────────────────────────────
#  Configuration
# ─────────────────────────────────────────────

SA_CREDENTIALS_PATH = os.environ.get("SA_CREDENTIALS_PATH", "")
GAS_BRIDGE_URL      = os.environ.get("GAS_BRIDGE_URL", "")
GAS_BRIDGE_SECRET   = os.environ.get("GAS_BRIDGE_SECRET", "")
HF_TOKEN            = os.environ.get("HF_TOKEN", "")
HF_REPO_ID          = os.environ.get("HF_REPO_ID", "adminlexzytech/phone-firmware")
CALLBACK_SECRET     = os.environ.get("BUILD_CALLBACK_SECRET") or os.environ.get("CALLBACK_SECRET", "")
FILE_ID             = os.environ.get("FILE_ID", "")
FILE_NAME           = os.environ.get("FILE_NAME", "")
CALLBACK_URL        = os.environ.get("CALLBACK_URL", "")
BUILD_ID            = os.environ.get("BUILD_ID", "")
EXCLUDE_PATTERNS    = [p.strip() for p in os.environ.get("EXCLUDE_PATTERNS", "").split("\n") if p.strip()]
SOURCE_TYPE         = os.environ.get("SOURCE_TYPE", "gdrive").strip().lower()
SOURCE_URL          = os.environ.get("SOURCE_URL", "").strip()
# ADDED 2026-09-24: brand/series/model the file registry holds for this file,
# as JSON. Empty for bulk-queue links and for WordPress sites not yet updated.
DEVICE_INFO         = os.environ.get("DEVICE_INFO", "").strip()
DUAL_BUILD          = os.environ.get("DUAL_BUILD", "false").strip().lower() in ("true", "1", "yes")
# Serve-time branding: store ONE brand-neutral artifact and let the Cloudflare
# Worker append the branding per request. When this is on, the build produces no
# branding files and no branded folder name, so the stored payload is byte-identical
# for every brand -- which is the whole point (see drive-architecture.md, 0.2).
# It supersedes DUAL_BUILD: there is nothing to dual-build when the only stored
# artifact is already the clean one.
SERVE_TIME_BRANDING = os.environ.get("SERVE_TIME_BRANDING", "false").strip().lower() in ("true", "1", "yes")
if SERVE_TIME_BRANDING:
    DUAL_BUILD = False

DRIVE_API_BASE   = "https://www.googleapis.com/drive/v3"
DRIVE_UPLOAD_BASE = "https://www.googleapis.com/upload/drive/v3"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"

BRAND_NAME  = "lexzytechinc.com"
BRAND_DOMAIN = "https://lexzytechinc.com"

WATERMARK_BRAND = (
    "╔═══════════════════════════════════════════════════════╗\n"
    "║                                                       ║\n"
    "║          Downloaded from LexzyTechInc.com              ║\n"
    "║                                                       ║\n"
    "║   This file was downloaded by a verified member of     ║\n"
    "║   LexzyTechInc.com. Redistribution without written     ║\n"
    "║   permission is strictly prohibited.                   ║\n"
    "║                                                       ║\n"
    "║   Website:   https://lexzytechinc.com                  ║\n"
    "║   YouTube:   https://youtube.com/@lexzytech             ║\n"
    "║   Telegram:  https://t.me/LexzyTechinc                 ║\n"
    "║   Facebook:  https://facebook.com/LexzyTech            ║\n"
    "║                                                       ║\n"
    "║   Thank you for supporting our platform!               ║\n"
    "╚═══════════════════════════════════════════════════════╝\n"
)

WATERMARK_README = (
    "================================================================\n"
    "   DOWNLOAD INFORMATION — LexzyTechInc.com\n"
    "================================================================\n\n"
    "This archive was generated by the LexzyTechInc.com\n"
    "download system.\n\n"
    "Source:      LexzyTechInc.com (Members Area)\n"
    "Usage:       Personal use only — do not redistribute\n"
    f"Generated:   {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Need Help?\n"
    "────────────────────────────────────────────────────────\n"
    "  Email:     support@lexzytechinc.com\n"
    "  Website:   https://lexzytechinc.com\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Upgrade to VIP\n"
    "────────────────────────────────────────────────────────\n"
    "  Instant downloads, no daily limits, priority support.\n"
    "  https://lexzytechinc.com/upgrade\n\n"
    "© LexzyTechInc.com — All Rights Reserved\n"
)

WATERMARK_URL = (
    "[InternetShortcut]\n"
    "URL=https://lexzytechinc.com\n"
    "IconIndex=0\n"
)


# ─────────────────────────────────────────────
#  Watermark Cleaning (ported from core.firmware.php → firmware_clean_filename)
# ─────────────────────────────────────────────

import re as _re

def is_generic_filename(name: str) -> bool:
    """Check if a filename is a generic placeholder, file ID, or hash."""
    if not name:
        return True
    clean = str(name).strip()
    clean_lower = clean.lower()

    # 1. Exact generic words
    generic_words = (
        "download", "download.zip", "download.rar", "download.7z",
        "file", "file.zip", "file.rar", "file.7z",
        "raw_download", "raw_download.zip",
        "archive", "archive.zip",
        "document", "document.zip",
        "none", "null", "undefined",
        "get", "get.zip", "link", "link.zip",
        "mega", "mega.zip", "mega.nz", "mega.io", "maga", "maga.zip",
        "mediafire", "mediafire.com", "gdrive", "drive"
    )
    if clean_lower in generic_words:
        return True

    # 2. Check base name without extension
    base = os.path.splitext(clean)[0]
    base_lower = base.lower()
    if base_lower in generic_words:
        return True

    # Check if name is purely a domain name (e.g. mega.nz, mediafire.com)
    if _re.match(r'^[a-zA-Z0-9-]+\.(?:com|net|org|nz|io|co|in|xyz|biz|info)$', clean, _re.I):
        return True

    # 3. Exact match with FILE_ID
    if FILE_ID:
        if clean == FILE_ID or clean_lower == FILE_ID.lower():
            return True
        if base == FILE_ID or base_lower == FILE_ID.lower():
            return True
        # If FILE_ID is mf_xxx, check raw xxx
        if FILE_ID.startswith("mf_"):
            raw_mf_id = FILE_ID[3:].lower()
            if base_lower == raw_mf_id or clean_lower == raw_mf_id:
                return True
        # If FILE_ID is mega_xxx, check raw xxx
        if FILE_ID.startswith("mega_"):
            raw_mega_id = FILE_ID[5:].lower()
            if base_lower == raw_mega_id or clean_lower == raw_mega_id:
                return True

    # 4. Check if it's purely an ID prefix like pvl_... or mf_ or mega_ followed only by ID chars
    if _re.match(r'^(?:mf_|pvl_|mega_)[a-zA-Z0-9_-]{6,60}$', base, _re.I):
        return True

    # 5. Raw Google Drive ID / hash pattern (25-45 random alphanumeric chars, but NOT containing firmware separators/words)
    if "." not in clean:
        # If it has underscores, spaces, or hyphens separating words, it is a real firmware name
        if "_" in clean or " " in clean:
            return False
        # If it contains common firmware indicators, it's not a hash
        fw_indicators = ('mt6', 'mt8', 'qualcomm', 'snapdragon', 'exynos', 'unisoc', 'spd', 'firmware', 'flash', 'stock', 'rom', 'scatter', 'ota', 'build', 'global')
        if any(ind in clean_lower for ind in fw_indicators):
            return False
        # Pure random alphanumeric 25-50 chars with no spaces or underscores
        if _re.match(r'^[a-zA-Z0-9]{25,50}$', clean):
            return True

    return False

# Shared with pvl_strip_site_watermarks() in pvl-engine/pvl-match.php and, through
# it, firmware_clean_filename() in core.firmware.php. All three used to keep their
# own hardcoded roster of competitor names, so a mirror nobody had added yet leaked
# its domain into stored filenames. Keep the three in step.
_WM_TLDS = 'com|net|org|info|co|in|io|xyz|biz|me|us|ru|ir|vn|id'
_WM_EXTS = 'zip|rar|7z|pac|tar|gz|tgz|bz2|iso|bin|img|md5|ozip|kdz|dz|sin|ftf|nb0|app'
# No hyphens in the label, 3 characters minimum, and a negative lookahead rather
# than  -- underscore is a word character, so  does not fire between "com"
# and "_". See the comment in pvl-match.php for what each of those prevents.
_WM_DOMAIN = r'[a-z0-9]{3,}\.(?:' + _WM_TLDS + r')(?![a-z0-9])'


def match_decode(text: str) -> str:
    """Undo percent-encoding. Mirrors pvl_match_decode() in pvl-match.php.

    Mirrors hand back href-encoded filenames and nothing upstream decodes
    them, so "V551%20%282%29.zip" kept its escapes through every cleaning
    rule -- the "(" and ")" patterns never matched -- and the identity keys
    picked up "282" and "29" as digit-bearing tokens. The same build then
    keyed differently depending on which mirror it arrived from.

    unquote, never unquote_plus: "+" is a real character in device names
    ("Pouvoir 4 Pro+") and unquote_plus would turn it into a space.
    """
    if not text or "%" not in text:
        return text
    # Decode to a fixed point. MediaFire hands back DOUBLE-encoded segments --
    # "%2528" is an encoded "%28" is an encoded "(" -- so one pass leaves
    # escapes the watermark rules cannot match. A fixed point is idempotent
    # for free: fully decoded text decodes to itself. Bounded so nested input
    # cannot spin.
    for _ in range(4):
        decoded = urllib.parse.unquote(text)
        if decoded == text:
            break
        text = decoded
    return text


def strip_site_watermarks(filename: str) -> str:
    """Remove any domain-shaped token from a filename, keeping the extension."""
    filename = match_decode(filename)
    if not filename:
        return ""

    ext = ""
    m = _re.match(r'^(.*?)(\.(?:' + _WM_EXTS + r'))$', filename, _re.I)
    if m:
        filename, ext = m.group(1), m.group(2)

    filename = _re.sub(r'[\s_-]*\[[^\]]*\][\s_-]*', '_', filename)
    filename = _re.sub(r'^[\s_(\[-]*(?:up[_\s-]+)?(?:www\.)?' + _WM_DOMAIN + r'[)\]_\s-]*',
                       '', filename, flags=_re.I)
    filename = _re.sub(r'[_\-\s]*(?:by[_\s-]*)?[(\[]?\s*(?:www\.)?' + _WM_DOMAIN + r'.*$',
                       '', filename, flags=_re.I)
    filename = _re.sub(r'_{2,}', '_', filename)
    filename = _re.sub(r'-{2,}', '-', filename)
    filename = filename.strip(' 	_-([')
    # FIXED 2026-09-24 (same as pvl_strip_site_watermarks in pvl-match.php):
    # the long/medium dashes of this site's own older branding
    # ("..._190417 — lexzytechinc.com.zip") were left behind as "..._190417 —".
    filename = filename.strip(' \t_-([–—')
    # ADDED 2026-09-24 (same rule in pvl-match.php): MobiFirmware's "+" between
    # a dated build number and its watermark goes with the watermark.
    filename = _re.sub(r'(\d{6}V\d+|V\d+_\d{6})\+(?=$|\()', r'\1', filename, flags=_re.I)

    return filename + ext


def clean_watermarks(filename: str) -> str:
    """Strip third-party site watermarks from firmware filenames and archive entries.
    Mirrors firmware_clean_filename() from core.firmware.php.
    """
    if not filename:
        return ""
    c = match_decode(filename)

    # 1. Bracket watermarks at start: [up_addROM.com]_, [Hovatek], [NaijaROM], [FirmwareFile], etc.
    c = _re.sub(r'^\[[^\]]+\]\s*_?', '', c)

    # 2. _[HardReset.info] or similar anywhere
    c = _re.sub(r'_?\[[^\]]+\]', '', c)

    # 3. Leading site domain prefix: "up_addROM.com_", "www.site.com-", "site.com_", etc.
    c = _re.sub(r'^(?:up_)?(?:www\.)?[a-zA-Z0-9]+\.(?:com|net|org|co|in|info|io|xyz|biz)[_\s-]+', '', c, flags=_re.I)

    # 4. _by_(FirmwareOS.com) -- specific pattern BEFORE general parens removal
    c = _re.sub(r'_?by_?\(?[a-zA-Z0-9_-]+(?:\.[a-zA-Z]{2,6})?\)?', '', c, flags=_re.I)

    # 5. Site names in parentheses: (MobiFirmware.com), (by_NaijaROM.Com), (firmwarefile.com), etc.
    c = _re.sub(r'\([^)]*\.(?:com|net|org|io|co|in|info|xyz|biz)[^)]*\)', '', c, flags=_re.I)

    # 6. Parenthesized by-watermarks even without .com: _(by_SiteName), _(by_NaijaROM), _(by_)
    c = _re.sub(r'_?\(by[_\s][^)]*\)', '', c, flags=_re.I)

    # 7. Standalone site name references in filenames
    c = _re.sub(r'[\s_-]*(?:addROM|TecnoFirmware|NaijaROM|FirmwareFile|MobiFirmware|XDAFirmware|Firmware4mobile|Firmware4mobiles|Repairmymobile|RepairMyMobile|FirmwareOS|HardReset|MobileGuru4|Rom2box|Samfw|EasyFirmware)\.(?:com|net|org|co|in|info|io|xyz)[\s_-]*', '_', c, flags=_re.I)

    # 8. _by_AnySiteName before extension
    c = _re.sub(r'_by_[a-zA-Z0-9_\.]+(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 9. _Repairmymobile / _ RepairMyMobile.in suffix before extension
    c = _re.sub(r'[\s_-]+Repairmymobile(?:\.(?:co|in))?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 10. _RMM suffix (RepairMyMobile abbreviation)
    c = _re.sub(r'_?RMM(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 11. _Firmware4mobile suffix before extension
    c = _re.sub(r'_?Firmware4mobiles?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 12. _MobileGuru4.com / _MobileGuru4 suffix before extension
    c = _re.sub(r'_?MobileGuru4(?:\.com)?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 13. Catch-all: trailing _by or _by_ before extension
    c = _re.sub(r'[_\s-]+by[_\s]*(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 14. Cleanup: double underscores/dashes
    c = _re.sub(r'_{2,}', '_', c)
    c = _re.sub(r'-{2,}', '-', c)

    # 15. Trailing underscore/dash before extension
    c = _re.sub(r'[_-]+\.(?=zip|rar|7z|pac|tar|gz|iso|bin|img)', '.', c, flags=_re.I)

    # 16. Leading underscore/dash
    c = _re.sub(r'^[_-]+', '', c)

    # 17. Generic pass: any remaining domain, named in the roster above or not.
    c = strip_site_watermarks(c)

    return c.strip()


# ─────────────────────────────────────────────
#  Progress Reporting
# ─────────────────────────────────────────────

_last_progress_time = 0
# The last thing reported, re-sent by the heartbeat (added 2026-09-24).
_progress_state = {"stage": "queued", "percent": 0, "message": "Build started"}
# Set once a final report (complete / error / duplicate) is sent. The
# heartbeat checks it under the same lock, so it can never send a progress
# report AFTER the final one -- WordPress would read that as "still
# building" and later mark a finished file as failed (fixed 2026-09-24).
_final_lock = threading.Lock()
_final_sent = False


def _mark_final():
    global _final_sent
    with _final_lock:
        _final_sent = True

def report_progress(stage: str, percent: int, message: str = "", force: bool = False):
    """Post a progress update to WordPress. Throttled to every 15 seconds unless forced."""
    global _last_progress_time
    _progress_state.update(stage=stage, percent=percent, message=message)
    now = time.time()
    if not force and (now - _last_progress_time) < 15:
        return
    _last_progress_time = now

    print(f"[{percent}%] {stage}: {message}")

    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    stage,
            "percent":  min(percent, 100),
            "message":  message,
        }, timeout=10)
    except Exception as e:
        print(f"  Warning: progress callback failed: {e}")


HEARTBEAT_SECONDS = 240


def start_heartbeat():
    """Re-send the current progress every 4 minutes (added 2026-09-24).

    Some steps are silent for a long time -- extracting a 20 GB archive, a
    slow ranged download of a throttled file. WordPress treats a build that
    has reported nothing for 20 minutes as dead and starts it again, so a
    healthy but quiet build must still say it is alive. Runs in the
    background and stops with the process.
    """
    def beat():
        while True:
            time.sleep(HEARTBEAT_SECONDS)
            with _final_lock:
                if _final_sent:
                    return
                s = dict(_progress_state)
                try:
                    requests.post(CALLBACK_URL, json={
                        "build_id": BUILD_ID,
                        "file_id":  FILE_ID,
                        "secret":   CALLBACK_SECRET,
                        "stage":    s["stage"],
                        "percent":  min(int(s["percent"]), 100),
                        "message":  s["message"],
                    }, timeout=10)
                except Exception:
                    pass

    threading.Thread(target=beat, daemon=True).start()


def report_error(message: str):
    """Report a fatal error to WordPress."""
    _mark_final()
    print(f"[ERROR] {message}")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "error",
            "percent":  0,
            "message":  message,
        }, timeout=10)
    except Exception:
        pass


def report_duplicate(existing_file_id: str, reason: str = ""):
    """Tell WordPress this source is already indexed, so no build was run.

    Sent as its own stage rather than an error: nothing went wrong, and the
    caller needs to distinguish "we already have this" from "the build failed"
    to avoid queueing a pointless retry.
    """
    _mark_final()
    print(f"[100%] Duplicate: already indexed as {existing_file_id} ({reason})")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "duplicate",
            "percent":  100,
            "message":  "Already cached from another source",
            "duplicate_of": existing_file_id,
        }, timeout=10)
    except Exception:
        pass


def report_complete(hf_url: str, file_size: int, hf_url_clean: str = "", file_size_clean: int = 0,
                    key_name: str = None):
    """Report successful completion to WordPress.

    hf_url_clean / file_size_clean are only sent when a DUAL_BUILD run
    actually produced an unwatermarked variant -- they're additive fields
    on the same payload, so a non-dual-build run (or a WordPress side that
    hasn't been updated to read them yet) is unaffected.
    """
    _mark_final()
    print(f"[100%] Complete: Upload verified ({file_size} bytes)")
    if hf_url_clean:
        print(f"[100%] Clean variant verified ({file_size_clean} bytes)")
    try:
        payload = {
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "complete",
            "percent":  100,
            "message":  "Build complete",
            "hf_url":   hf_url,
            "hf_size":  file_size,
        }
        if hf_url_clean:
            payload["hf_url_clean"]  = hf_url_clean
            payload["hf_size_clean"] = file_size_clean
        if key_name is not None:
            # ADDED 2026-09-24. The stored name now carries added detail
            # (brand, series, chipset). Duplicate detection must keep reading
            # the vendor's own name: "Tecno_Phantom_X2_(AD8-...)" and
            # "AD8-..." are one build, but "x2" would split their keys.
            # Empty means the file's name carries no identity at all.
            payload["key_name"] = key_name
        requests.post(CALLBACK_URL, json=payload, timeout=10)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  Google Drive Authentication (Service Account)
# ─────────────────────────────────────────────

_cached_token = None
_token_expiry = 0

def get_access_token() -> str:
    """Get a Google OAuth2 access token using the Service Account."""
    global _cached_token, _token_expiry

    if _cached_token and time.time() < _token_expiry:
        return _cached_token

    with open(SA_CREDENTIALS_PATH, "r") as f:
        creds = json.load(f)

    now = int(time.time())
    payload = {
        "iss":   creds["client_email"],
        "scope": "https://www.googleapis.com/auth/drive",
        "aud":   GOOGLE_TOKEN_URL,
        "iat":   now,
        "exp":   now + 3600,
    }

    token = jwt.encode(payload, creds["private_key"], algorithm="RS256")
    resp = requests.post(GOOGLE_TOKEN_URL, data={
        "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "assertion":  token,
    }, timeout=30)
    resp.raise_for_status()
    data = resp.json()

    _cached_token = data["access_token"]
    _token_expiry = now + data.get("expires_in", 3600) - 60
    return _cached_token


# ─────────────────────────────────────────────
#  Google Drive File Metadata
# ─────────────────────────────────────────────

def get_file_metadata(file_id: str) -> dict:
    """Fetch file metadata from Google Drive."""
    token = get_access_token()
    resp = requests.get(f"{DRIVE_API_BASE}/files/{file_id}", params={
        "fields": "id,name,mimeType,size",
        "supportsAllDrives": "true",
    }, headers={"Authorization": f"Bearer {token}"}, timeout=30)
    resp.raise_for_status()
    return resp.json()


# ─────────────────────────────────────────────
#  Archive & Download Integrity Verification
# ─────────────────────────────────────────────

EXTRACTABLE_EXTENSIONS = {'.zip', '.rar', '.7z', '.tar', '.gz', '.tgz', '.bz2', '.xz'}
STANDALONE_EXTENSIONS  = {'.iso', '.img', '.pac', '.bin', '.exe', '.tar.md5'}


def verify_archive_integrity(filepath: str, original_name: str = "") -> tuple[bool, str]:
    """
    Test whether a downloaded archive is intact or corrupted.
    Returns (True, "OK") or (False, error_reason).
    """
    if not os.path.exists(filepath):
        return False, "File does not exist"

    size = os.path.getsize(filepath)
    if size < 1024:
        return False, f"File suspiciously small ({size} bytes)"

    name = original_name or os.path.basename(filepath)
    ext = os.path.splitext(name)[1].lower()

    # Standalone files (.pac, .bin, .img, .iso, etc.) are flashed directly and not archives
    if ext in STANDALONE_EXTENSIONS:
        return True, "Standalone file (non-archive)"

    # Magic byte signature check
    try:
        with open(filepath, "rb") as f:
            header = f.read(16)
        if ext == ".zip" and not (header.startswith(b"PK\x03\x04") or header.startswith(b"PK\x05\x06") or header.startswith(b"PK\x07\x08")):
            return False, f"Invalid ZIP magic bytes: {header[:8]!r}"
        if ext == ".rar" and not header.startswith(b"Rar!\x1a\x07"):
            return False, f"Invalid RAR magic bytes: {header[:8]!r}"
        if ext == ".7z" and not header.startswith(b"7z\xbc\xaf\x27\x1c"):
            return False, f"Invalid 7Z magic bytes: {header[:8]!r}"
    except Exception as e:
        return False, f"Header read error: {e}"

    # Primary integrity test: run 7z t (tests CRC32 of all internal streams in memory)
    try:
        res = subprocess.run(["7z", "t", "-y", filepath],
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if res.returncode == 0:
            return True, "7z integrity test passed"
        else:
            err_output = res.stderr.decode("utf-8", errors="replace").strip() or res.stdout.decode("utf-8", errors="replace").strip()
            err_lines = [line.strip() for line in err_output.splitlines() if line.strip()]
            reason = " | ".join(err_lines[-3:]) if err_lines else f"7z exit code {res.returncode}"
            return False, f"7z test failed: {reason}"
    except FileNotFoundError:
        # Fallback to python zipfile.testzip() if 7z binary is absent
        if ext == ".zip" or zipfile.is_zipfile(filepath):
            try:
                with zipfile.ZipFile(filepath, "r") as zf:
                    corrupt_member = zf.testzip()
                    if corrupt_member is not None:
                        return False, f"ZIP CRC failed on member: {corrupt_member}"
                    return True, "zipfile testzip passed"
            except Exception as e:
                return False, f"zipfile test failed: {e}"

    return True, "Integrity assumed (no testing tool available)"


# ─────────────────────────────────────────────
#  Download Cascade (mirrors PHP pvl_sa_download_to_temp)
# ─────────────────────────────────────────────

def download_file(file_id: str, dest_path: str) -> bool:
    """
    Download a file from storage source (MEGA, MediaFire, or Google Drive).
    Validates archive integrity after download; if corrupted, unlinks and tries next method.
    """
    global FILE_NAME

    # Resolve the display name ONCE, from the same signals the branches below
    # test. Previously each branch spelled its own brand name by hand, which
    # is how a Google Drive build could surface "Connecting to MEGA source...".
    SRC = source_label(SOURCE_TYPE, file_id, SOURCE_URL or "")

    # ─── MEGA Source ───
    is_mega = (SOURCE_TYPE == "mega") or file_id.startswith("mega_") or is_mega_url(SOURCE_URL or "")
    if is_mega:
        report_progress("downloading", 10, f"Connecting to {SRC}...", force=True)

        def on_mega_dl_progress(pct: int, msg: str):
            overall_pct = 10 + int(pct * 0.65)
            clean_msg = msg[:90] if msg else f"{pct}%"
            report_progress("downloading", overall_pct, f"Downloading from {SRC} ({clean_msg})")

        ok, real_name = mega_download(file_id, SOURCE_URL or "", dest_path, progress_callback=on_mega_dl_progress)
        if not ok:
            return False
        if real_name and not is_generic_filename(real_name):
            FILE_NAME = real_name
        if os.path.exists(dest_path):
            ok, reason = verify_archive_integrity(dest_path, FILE_NAME)
            if not ok:
                print(f"  MEGA download failed integrity check: {reason}")
                try:
                    os.unlink(dest_path)
                except Exception:
                    pass
                return False
            print(f"  MEGA download verified intact: {reason}")
            return True
        return False

    # ─── MediaFire Source ───
    is_mediafire = (SOURCE_TYPE == "mediafire") or file_id.startswith("mf_") or ("mediafire.com" in (SOURCE_URL or ""))
    if is_mediafire:
        report_progress("downloading", 10, f"Connecting to {SRC}...", force=True)
        success = mediafire_download(file_id, dest_path)
        if success and os.path.exists(dest_path):
            ok, reason = verify_archive_integrity(dest_path, FILE_NAME)
            if not ok:
                print(f"  MediaFire download failed integrity check: {reason}")
                try:
                    os.unlink(dest_path)
                except Exception:
                    pass
                return False
            print(f"  MediaFire download verified intact: {reason}")
            return True
        return False

    # ─── Google Drive Cascade with Integrity Verification ───
    methods = [
        # Free, no storage, no temp folder, no bridge -- and it works on files
        # the public-link route reports as quota-blocked. Try it first.
        ("Signed URL", 4, lambda: signed_url_download(file_id, dest_path)),
        # Added 2026-09-24. Right after Signed URL: when the whole-file request
        # is refused as over quota, the same file in slices usually is not.
        ("Ranged download", 5, lambda: ranged_download(file_id, dest_path)),
        ("GAS copy", 5, lambda: gas_try_copy(file_id, dest_path)),
        ("GAS folder download", 10, lambda: gas_try_folder_download(file_id, dest_path)),
        ("Web download URL", 15, lambda: web_download(file_id, dest_path)),
        ("API download", 20, lambda: api_download(file_id, dest_path)),
    ]

    for attempt in range(1, 3):
        if attempt > 1:
            print(f"  Retrying Google Drive cascade (pass {attempt}/2)...")
            time.sleep(3)

        for name, pct, method in methods:
            # Strategy names ("GAS copy", "API download") are internal
            # quota-workaround details. They go to the build log only; the
            # user sees one steady message naming the actual source.
            print(f"  Strategy: {name}")
            report_progress("downloading", pct, f"Fetching from {SRC}...", force=True)
            try:
                success = method()
            except Exception as e:
                print(f"  {name} raised exception: {e}")
                success = False

            if success and os.path.exists(dest_path):
                ok, reason = verify_archive_integrity(dest_path, FILE_NAME)
                if ok:
                    print(f"  Download verified intact via {name}: {reason}")
                    return True
                else:
                    print(f"  Download via {name} failed integrity check: {reason}")
                    try:
                        os.unlink(dest_path)
                    except Exception:
                        pass
                    print(f"  Discarded corrupt file, falling through to next download method...")

    return False


def mediafire_download(file_id: str, dest_path: str) -> bool:
    """Download a file from MediaFire by resolving direct link from public page."""
    global FILE_NAME
    import re

    quickkey = file_id.replace("mf_", "").strip()
    page_url = SOURCE_URL if (SOURCE_URL and "mediafire.com" in SOURCE_URL) else f"https://www.mediafire.com/file/{quickkey}"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    }

    try:
        session = requests.Session()
        resp = session.get(page_url, headers=headers, timeout=30)
        if resp.status_code != 200:
            print(f"  MediaFire page returned HTTP {resp.status_code}")
            return False

        html = resp.text

        # Extract direct download link
        direct_url = None
        m = re.search(r'href=["\'](https?://download\d+\.mediafire\.com/[^"\']+)["\']', html, re.I)
        if m:
            direct_url = m.group(1)
        else:
            m = re.search(r'id=["\']downloadButton["\'][^>]*href=["\']([^"\']+)["\']', html, re.I)
            if m:
                direct_url = m.group(1)
            else:
                m = re.search(r'aria-label=["\']Download file["\'][^>]*href=["\']([^"\']+)["\']', html, re.I)
                if m:
                    direct_url = m.group(1)
                else:
                    m = re.search(r'https?://(?:www\.)?mediafire\.com/file_download/[^\s"\'<>]+', html, re.I)
                    if m:
                        direct_url = m.group(0)

        if not direct_url:
            print(f"  Could not extract direct download URL from MediaFire page: {page_url}")
            return False

        # Extract original filename from MediaFire HTML, direct URL, or SOURCE_URL
        scraped_fn = None
        fn_patterns = [
            r'<div[^>]+class=["\'][^"\']*(?:file-name|filename|filename-text)[^"\']*["\'][^>]*>([^<]+)</div>',
            r'class=["\']filename["\'][^>]*>([^<]+)<',
            r'<meta property=["\']og:title["\'] content=["\']([^"\']+)["\']',
            r'<title>([^<]+)</title>',
        ]
        for pat in fn_patterns:
            fn_m = re.search(pat, html, re.I)
            if fn_m:
                cand = fn_m.group(1).strip()
                # Strip trailing " - MediaFire" if from title
                cand = re.sub(r'\s*-\s*MediaFire\s*$', '', cand, flags=re.I).strip()
                if cand and not is_generic_filename(cand):
                    scraped_fn = cand
                    break
        
        if not scraped_fn and direct_url:
            url_fn = direct_url.split("/")[-1].split("?")[0]
            if url_fn and not is_generic_filename(url_fn):
                scraped_fn = urllib.parse.unquote(url_fn)

        if not scraped_fn and SOURCE_URL:
            src_parts = [p for p in SOURCE_URL.split("?")[0].split("/") if p and p.lower() not in ("file", "view", "download", "edit")]
            if src_parts and not is_generic_filename(src_parts[-1]):
                scraped_fn = urllib.parse.unquote(src_parts[-1])

        if scraped_fn:
            scraped_clean = clean_watermarks(scraped_fn)
            if is_generic_filename(FILE_NAME) or ("." in scraped_clean and "." not in FILE_NAME) or FILE_NAME.startswith("mf_"):
                FILE_NAME = scraped_clean
                print(f"  Scraped MediaFire filename: {FILE_NAME}")

        print(f"  MediaFire direct download link found: {direct_url}")
        report_progress("downloading", 20, f"Downloading from MediaFire ({FILE_NAME})...")

        dl_resp = session.get(direct_url, headers=headers, stream=True, timeout=60)
        if dl_resp.status_code != 200:
            print(f"  MediaFire stream returned HTTP {dl_resp.status_code}")
            return False

        # Check Content-Disposition for filename
        cd = dl_resp.headers.get("Content-Disposition", "")
        if "filename=" in cd:
            cd_fn = re.search(r'filename=["\']?([^"\';]+)', cd)
            if cd_fn:
                cd_name = clean_watermarks(cd_fn.group(1).strip())
                if is_generic_filename(FILE_NAME) or ("." in cd_name and "." not in FILE_NAME) or FILE_NAME.startswith("mf_"):
                    FILE_NAME = cd_name
                    print(f"  Content-Disposition filename: {FILE_NAME}")

        total = int(dl_resp.headers.get("Content-Length", 0))
        downloaded = 0

        with open(dest_path, "wb") as f:
            for chunk in dl_resp.iter_content(chunk_size=65536):
                f.write(chunk)
                downloaded += len(chunk)
                if total > 0:
                    pct = int((downloaded / total) * 60) + 20
                    report_progress("downloading", pct,
                                    f"Downloaded {downloaded // (1024*1024)} / {total // (1024*1024)} MB")

        size = os.path.getsize(dest_path)
        if size < 100:
            print("  MediaFire downloaded file is too small (<100 bytes)")
            try:
                os.unlink(dest_path)
            except Exception:
                pass
            return False

        if total > 0 and size != total:
            print(f"  MediaFire download incomplete: got {size:,} bytes, expected {total:,} bytes")
            try:
                os.unlink(dest_path)
            except Exception:
                pass
            return False

        print(f"  MediaFire download successful: {size:,} bytes")
        return True

    except Exception as e:
        print(f"  MediaFire download exception: {e}")
        traceback.print_exc()
        return False


def gas_try_copy(file_id: str, dest_path: str) -> bool:
    """GAS Approach A: Server-side copy with fresh quota."""
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action": "copy",
            "fileId": file_id,
            "secret": GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        if not data.get("success"):
            print(f"  GAS copy failed: {data.get('error', 'unknown')}")
            return False

        copy_id = data["copyId"]
        download_url = data["downloadUrl"]
        print(f"  GAS copy created: {copy_id}")

        # Download the copy
        success = stream_download(download_url, dest_path, auth=None)

        # Cleanup the copy
        try:
            requests.get(GAS_BRIDGE_URL, params={
                "action": "cleanup",
                "copyId": copy_id,
                "secret": GAS_BRIDGE_SECRET,
            }, timeout=30)
        except Exception:
            pass

        return success

    except Exception as e:
        print(f"  GAS copy error: {e}")
        return False


def gas_poll_takeout(job_id: str, budget_s: int = 900) -> dict:
    """Poll a Takeout export job the bridge started but could not finish.

    Apps Script caps a run at ~6 minutes and a multi-gigabyte folder takes
    longer than that to zip, so the bridge hands back the job id. The job
    itself survives, so the only thing needed is patience -- and the runner
    has plenty.
    """
    delays = [10, 15, 20, 30, 30, 45, 60, 60, 90, 90, 120, 120, 150]
    spent = 0
    for d in delays:
        if spent >= budget_s:
            break
        time.sleep(d)
        spent += d
        try:
            r = requests.get(GAS_BRIDGE_URL, params={
                "action": "takeout_status",
                "jobId":  job_id,
                "secret": GAS_BRIDGE_SECRET,
            }, timeout=60)
            data = r.json()
        except Exception as e:
            print(f"  Takeout poll error: {e}")
            continue
        if data.get("success") and data.get("signedUrl"):
            print(f"  Takeout job finished after {spent}s: "
                  f"{data.get('fileName')} ({data.get('size')} bytes)")
            return data
        print(f"  Takeout job {job_id}: {data.get('status')} ({spent}s elapsed)")
    return {}


def gas_try_folder_download(file_id: str, dest_path: str) -> bool:
    """GAS Approach B: Folder + shortcut + signed URL."""
    # Required, not stylistic: this function ASSIGNS FILE_NAME when the bridge
    # reports the real name, and in Python a single assignment anywhere in a
    # function makes the name local for the WHOLE function. Without this, the
    # read in the request below raised UnboundLocalError before any network
    # call, so the folder route failed on every build from 6402327 onward.
    # test_worker_globals.py pins it.
    global FILE_NAME
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action":   "folder_download",
            "fileId":   file_id,
            "fileName": FILE_NAME,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        # The bridge reports every endpoint it tried. Print them: "no signed
        # URL" on its own says nothing, whereas "folder:anon 404, file:auth
        # 303" says exactly where the mechanism stands.
        for a in (data.get("attempts") or []):
            if "error" in a:
                print(f"    bridge {a.get('mode')}: error {a['error']}")
            else:
                print(f"    bridge {a.get('mode')}: HTTP {a.get('status')}, "
                      f"location {a.get('location')}")

        if not data.get("success"):
            print(f"  GAS folder failed: {data.get('error', 'unknown')}")
            # Older bridges hand back the temp folder id on failure and delete
            # nothing, so every failed attempt used to leak a folder forever.
            # Newer ones clean up themselves and say so with cleanedUp.
            stale = data.get("folderId")
            if stale and not data.get("cleanedUp"):
                print(f"  Cleaning up leaked temp folder {stale}")
                cleanup_gas_folder(stale)
            return False

        # The bridge may still be zipping. The export job outlives its run,
        # so keep polling instead of discarding the work.
        if data.get("pending") and data.get("jobId"):
            print(f"  Takeout job {data['jobId']} still building; polling")
            data = gas_poll_takeout(data["jobId"]) or {}
            for a in (data.get("attempts") or []):
                print(f"    bridge {a.get('mode')}: {a.get('status')}")
            if not data.get("signedUrl"):
                print("  Takeout job did not finish in time")
                return False

        folder_id  = data.get("folderId")     # None when the file id worked
        signed_url = data["signedUrl"]
        via = data.get("via", "folder")

        # FIXED 2026-09-24. via == "file" is the bridge running the SAME
        # POST /uc on the SAME file id that "Signed URL" already tried at the
        # top of the cascade. It returns only because the bridge checks it
        # with a small ranged request, which a quota-blocked file answers;
        # the whole-file download below then gets 429, and the retry loop
        # spent about 8 minutes of runner time on every blocked build before
        # giving up. (The v5 bridge never returned this at all: its bodyless
        # POST always failed at once, so the cascade moved on immediately.)
        if via == "file":
            print("  GAS folder: bridge returned the same file link Signed URL "
                  "already tried; moving on")
            return False

        # A Takeout archive URL is SESSION BOUND. Fetched with no credentials
        # it answers 302 -> accounts.google.com/ServiceLogin, even seconds
        # after the job reports SUCCEEDED -- measured on a fresh job. So it
        # must carry the identity that created it, which the bridge returns.
        dl_auth = None
        if data.get("requiresAuth") and data.get("token"):
            dl_auth = "Bearer " + data["token"]
            print("  Archive URL requires the bridge identity; using its token")
        if data.get("fileName") and not is_generic_filename(data["fileName"]):
            if data["fileName"] != FILE_NAME:
                print(f"  Takeout reports filename {data['fileName']}")
            FILE_NAME = data["fileName"]
        if folder_id:
            print(f"  GAS folder created: {folder_id}, got signed URL (via {via})")
        else:
            # The file-id path needs no temp folder at all, so there is
            # nothing to clean up afterwards.
            print(f"  GAS signed URL obtained with no temp folder (via {via})")

        # Download the folder ZIP.
        #
        # Google zips a folder ASYNCHRONOUSLY. The signed URL is handed back
        # immediately, but for a large folder the archive behind it does not
        # exist yet -- a 9 GB folder takes minutes to assemble. A single
        # attempt cannot tell "not ready yet" from "dead link".
        #
        # The old code took that single attempt and then called
        # cleanup_gas_folder() on failure, which deletes the folder and with
        # it the job URL. A slow zip was therefore indistinguishable from a
        # broken one AND unrecoverable: there was nothing left to retry
        # against. Poll with backoff, and only clean up once we have really
        # given up.
        zip_path = dest_path + ".folder.zip"
        RETRY_DELAYS = [0, 15, 30, 60, 120, 240]   # ~7.75 minutes total
        downloaded = False
        for i, delay in enumerate(RETRY_DELAYS):
            if delay:
                print(f"  Folder ZIP not ready; waiting {delay}s "
                      f"(attempt {i + 1}/{len(RETRY_DELAYS)})")
                time.sleep(delay)
            if stream_download(signed_url, zip_path, auth=dl_auth):
                downloaded = True
                break
        if not downloaded:
            print(f"  Folder ZIP never became available after "
                  f"{sum(RETRY_DELAYS)}s; giving up")
            if folder_id:
                cleanup_gas_folder(folder_id)
            return False

        # What comes back may or may not be a wrapper.
        #
        # Measured against four real archives downloaded this way: Google
        # returns the ORIGINAL file, byte for byte, named after the folder
        # with a "-001" suffix. Its contents are the firmware package's own
        # structure, not a zip holding a zip.
        #
        # extract_from_google_zip() pulls out the single largest entry, so
        # running it on such a file would keep the one big .pac and throw
        # away Credits.txt, Driver/ and the package layout -- turning a
        # complete package into a loose blob. Only unwrap when the archive
        # really is a wrapper: one lone archive entry inside.
        if looks_like_folder_wrapper(zip_path):
            print("  Folder ZIP is a wrapper; extracting the archive inside")
            success = extract_from_google_zip(zip_path, dest_path)
            os.unlink(zip_path)
        else:
            print("  Folder ZIP is the firmware archive itself; keeping as-is")
            os.replace(zip_path, dest_path)
            success = True

        if folder_id:
            cleanup_gas_folder(folder_id)
        return success

    except Exception as e:
        print(f"  GAS folder error: {e}")
        return False


def signed_url_download(file_id: str, dest_path: str) -> bool:
    """Approach 0: POST /uc for a signed URL, then stream it with no auth.

    Google serves a public Drive file by two routes that do NOT behave alike.
    Measured side by side on one file at one moment:

        drive.usercontent.google.com/download?id=...   200  text/html
        POST drive.google.com/uc?export=download&id=.. 303  -> signed URL
          doc-0s-2c-docs.googleusercontent.com/...     206  application/zip

    The first is the public-link route and carries the per-file download
    quota; the second hands back a short-lived signed URL that serves the
    bytes. web_download() and the WordPress probe both used the first, so a
    file that downloads perfectly well was treated as quota-blocked and sent
    down the GAS copy / temp-folder / manual path for nothing.

    This costs nothing to try, needs no Drive storage, no temp folder and no
    bridge, so it goes first in the cascade.

    The POST needs a body: a bodyless POST to /uc answers 411 Length Required,
    never a 303.
    """
    global FILE_NAME
    try:
        resp = requests.post(
            f"https://drive.google.com/uc?export=download&id={file_id}&confirm=t",
            data="", allow_redirects=False, timeout=30)
        if resp.status_code not in (302, 303):
            print(f"  Signed URL: /uc answered {resp.status_code}, not a redirect")
            return False

        signed = resp.headers.get("Location", "")
        if not signed:
            print("  Signed URL: redirect carried no Location")
            return False

        # A 303 is not proof. Prove it serves before committing to a
        # multi-gigabyte transfer.
        #
        # A Range probe is cheap and works for a FILE. It does NOT work for a
        # folder zip: Google builds those on the fly, so there is no length to
        # range over and the answer is 416 -- which is not a failure, just an
        # unanswerable question. Measured on a live, freshly created folder:
        #
        #   Range: bytes=0-63  ->  416 Requested range not satisfiable
        #   plain GET          ->  500 Internal Server Error  (21 bytes)
        #
        # So: try Range first, and on 416 fall back to a STREAMED plain GET
        # that reads a few hundred bytes and is then closed. Never download the
        # whole body just to identify it.
        probe = requests.get(signed, headers={"Range": "bytes=0-63"},
                             timeout=30, allow_redirects=True)
        ctype = (probe.headers.get("Content-Type") or "").lower()

        if probe.status_code == 416:
            probe.close()
            probe = requests.get(signed, timeout=30, allow_redirects=True,
                                 stream=True)
            ctype = (probe.headers.get("Content-Type") or "").lower()
            head = next(probe.iter_content(512), b"")
            probe.close()
            if probe.status_code != 200 or "text/" in ctype or len(head) < 4:
                print(f"  Signed URL: streamed probe returned "
                      f"{probe.status_code} {ctype!r}, {len(head)} bytes")
                return False
        elif probe.status_code not in (200, 206) or "text/" in ctype:
            print(f"  Signed URL: probe returned {probe.status_code} {ctype!r}")
            return False

        # Google states the true filename here. This is the same name the
        # archive carries in its own root folder, and it is very often the
        # only good name available -- the URL path has none at all.
        real_name = ""
        disp = probe.headers.get("Content-Disposition") or ""
        # RFC 5987 form:  filename*=UTF-8''P661N_MT6833_GL_V124_240911.zip
        m = _re.search(r"filename\*=UTF-8''([^;]+)", disp)
        if m:
            real_name = urllib.parse.unquote(m.group(1))
        else:
            m = _re.search(r'filename="([^"]+)"', disp)
            if m:
                real_name = m.group(1)
        if real_name and not is_generic_filename(real_name):
            if real_name != FILE_NAME:
                print(f"  Signed URL: real filename is {real_name}")
            FILE_NAME = real_name

        print(f"  Signed URL obtained ({probe.status_code}, {ctype})")
        return stream_download(signed, dest_path, auth=None)

    except Exception as e:
        print(f"  Signed URL error: {e}")
        return False


# How long the ranged route may keep asking before the cascade moves on. The
# job itself is allowed 350 minutes (build.yml); this leaves room for the
# repack and the Hugging Face upload of a large file.
RANGED_DEADLINE_SECONDS = 270 * 60


def ranged_download(file_id: str, dest_path: str) -> bool:
    """Approach 0b: fetch the file in byte ranges (added 2026-09-24).

    WHY: Drive's "quota exceeded" answer is given to a request for the WHOLE
    file. The same file, asked for in slices, is still served -- measured on
    GitHub runners 9 times out of 9, across 3 files and 4 addresses, with every
    re-checked sample byte-identical. Signed URL (the step before this) asks
    for the whole file, which is why it gets 429 on a blocked file.

    The fetch is written into its OWN file and renamed into place only when
    complete, so a partial result can never be mistaken for a download by the
    rest of the cascade, and no leftover can be mistaken for a finished one.
    """
    global FILE_NAME
    from ranged_fetch import RangedFetcher, RangedFetchError, drive_url, probe

    url = drive_url(file_id)
    try:
        size, served_name = probe(url)
    except Exception as e:
        print(f"  Ranged download: not available ({e})")
        return False

    if served_name and not is_generic_filename(served_name):
        if served_name != FILE_NAME:
            print(f"  Ranged download: real filename is {served_name}")
        FILE_NAME = served_name

    work_path = dest_path + ".ranged"
    mb = 1024 * 1024

    def on_progress(done, total):
        pct = 10 + int(68 * done / max(total, 1))
        report_progress("downloading", pct,
                        f"Downloading ({done // mb} / {total // mb} MB)")

    print(f"  Ranged download: {size // mb} MB in 8 MB slices")
    fetcher = RangedFetcher(url, work_path, size=size, on_progress=on_progress,
                            deadline=RANGED_DEADLINE_SECONDS)
    try:
        got, secs, reqs = fetcher.run()
    except RangedFetchError as e:
        print(f"  Ranged download failed: {e}")
        return False

    if os.path.getsize(work_path) != size:
        print(f"  Ranged download: size mismatch ({os.path.getsize(work_path)} != {size})")
        return False

    os.replace(work_path, dest_path)
    fetcher.cleanup()
    rate = (got / mb / secs) if secs else 0
    print(f"  Ranged download complete: {got // mb} MB in {secs:.0f}s "
          f"({rate:.1f} MB/s, {reqs} requests)")
    return True


def web_download(file_id: str, dest_path: str) -> bool:
    """Approach 2: Web download URL with SA Bearer token."""
    try:
        token = get_access_token()
        url = f"https://drive.usercontent.google.com/download?id={file_id}&export=download&confirm=t"
        return stream_download(url, dest_path, auth=f"Bearer {token}")
    except Exception as e:
        print(f"  Web download error: {e}")
        return False


def api_download(file_id: str, dest_path: str) -> bool:
    """Approach 3: Standard Google Drive API download."""
    try:
        token = get_access_token()
        url = f"{DRIVE_API_BASE}/files/{file_id}"
        return stream_download(url, dest_path, auth=f"Bearer {token}",
                               params={"alt": "media", "supportsAllDrives": "true"})
    except Exception as e:
        print(f"  API download error: {e}")
        return False


def stream_download(url: str, dest_path: str, auth: str = None, params: dict = None) -> bool:
    """Stream a URL to a local file. Reports progress during download."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
    if auth:
        headers["Authorization"] = auth

    try:
        resp = requests.get(url, headers=headers, params=params, stream=True, timeout=30, allow_redirects=True)
    except Exception as e:
        print(f"  Stream request failed: {e}")
        return False

    if resp.status_code != 200:
        print(f"  Download returned HTTP status {resp.status_code}")
        return False

    # Reject obvious HTML error pages (Google returns 200 + text/html for quota errors)
    content_type = resp.headers.get("Content-Type", "")
    if "text/html" in content_type:
        snippet = resp.content[:500].decode("utf-8", errors="replace")
        print(f"  Download returned HTML: {snippet[:200]}")
        return False

    total = int(resp.headers.get("Content-Length", 0))
    downloaded = 0

    with open(dest_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=65536):
            f.write(chunk)
            downloaded += len(chunk)
            if total > 0:
                pct = int((downloaded / total) * 60) + 20  # 20-80% range
                report_progress("downloading", pct,
                                f"Downloaded {downloaded // (1024*1024)} / {total // (1024*1024)} MB")

    size = os.path.getsize(dest_path)

    # Check if it's actually HTML despite the Content-Type header lying
    with open(dest_path, "rb") as f:
        head = f.read(256)
    if b"<!DOCTYPE" in head or b"<html" in head or b"Quota exceeded" in head:
        snippet = head[:200].decode("utf-8", errors="replace")
        print(f"  Download is HTML despite Content-Type ({content_type}): {snippet[:150]}")
        try:
            os.unlink(dest_path)
        except Exception:
            pass
        return False

    # Reject suspiciously small files (any real firmware ZIP is at least several MB)
    if size < 1024:
        print(f"  Download too small: {size} bytes (expected a real file, not an error page)")
        try:
            os.unlink(dest_path)
        except Exception:
            pass
        return False

    # Reject truncated downloads if Content-Length was provided
    if total > 0 and size != total:
        print(f"  Download incomplete: got {size:,} bytes, expected {total:,} bytes")
        try:
            os.unlink(dest_path)
        except Exception:
            pass
        return False

    print(f"  Downloaded {size:,} bytes")
    return True


def looks_like_folder_wrapper(zip_path: str) -> bool:
    """Is this a Google folder ZIP wrapping ONE archive, or the archive itself?

    Measured on four real downloads from the folder route: Google returns the
    original file unchanged -- byte-identical to the size Drive reports for
    the target -- named "<FolderName>-001.zip". Its entries are the firmware
    package's own layout:

        Itel_VistaTab_11_..._SPD/Credits.txt
        Itel_VistaTab_11_..._SPD/Driver/
        Itel_VistaTab_11_..._SPD/Firmware/<5.3 GB .pac>

    Unwrapping that keeps only the .pac and discards everything else, so the
    "-001" suffix must NOT be used as the trigger. The real question is what
    is inside: a wrapper holds one archive and nothing that matters.

    Reads the central directory only -- no extraction, so a 9 GB file costs
    the same as a small one. Fails closed: on any error, say "not a wrapper",
    because keeping an archive whole is recoverable and gutting one is not.
    """
    ARCHIVE_EXTS = (".zip", ".rar", ".7z", ".tar", ".gz", ".tgz", ".pac",
                    ".kdz", ".dz", ".ofp", ".ops", ".bin", ".img", ".md5")
    try:
        with zipfile.ZipFile(zip_path) as zf:
            files = [i for i in zf.infolist() if not i.is_dir()]
    except Exception as e:
        print(f"  Could not inspect archive ({e}); treating as not-a-wrapper")
        return False

    if not files:
        return False

    archives = [i for i in files if i.filename.lower().endswith(ARCHIVE_EXTS)]
    if len(archives) != 1:
        return False

    # One archive inside, and it is the overwhelming majority of the content.
    # The rest would be a stray readme or .url, never a firmware payload.
    inner = archives[0]
    total = sum(i.file_size for i in files) or 1
    if inner.file_size / total < 0.95:
        return False

    # A real firmware package can also contain exactly one big .pac beside a
    # Credits.txt -- which matches everything above. Distinguish by depth:
    # a wrapper puts its archive at the top, a package buries it in a
    # subfolder such as Firmware/.
    depth = inner.filename.replace("\\", "/").strip("/").count("/")
    return depth <= 1


def extract_from_google_zip(zip_path: str, dest_path: str) -> bool:
    """Extract the largest non-directory file from a Google folder ZIP.

    Also recovers the REAL filename. Google's folder ZIP preserves the name
    Drive holds, which is very often the only good name in the whole pipeline
    -- the job that produced "rom file, lexzytechinc.com.zip" is exactly the
    case this rescues. The name used to be printed and thrown away.

    Updates the FILE_NAME global rather than changing the return type, because
    the Drive cascade in download_file() dispatches through
    `lambda: ... -> bool` and a tuple would break every branch. This mirrors
    what the MEGA path already does with its own recovered name.
    """
    global FILE_NAME
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            target = None
            target_size = 0
            for info in zf.infolist():
                if info.is_dir() or info.filename.startswith("."):
                    continue
                if info.file_size > target_size:
                    target = info
                    target_size = info.file_size

            if not target:
                print("  No files found in folder ZIP")
                return False

            with zf.open(target) as src, open(dest_path, "wb") as dst:
                shutil.copyfileobj(src, dst)

            print(f"  Extracted: {target.filename} ({target_size:,} bytes)")

            # Keep the real name. basename() because ZIP entries carry their
            # folder path, and is_generic_filename() so a Drive folder that
            # genuinely holds "download.zip" does not overwrite a better name
            # we already had.
            real_name = os.path.basename(target.filename)
            if real_name and not is_generic_filename(real_name):
                if real_name != FILE_NAME:
                    print(f"  Recovered real filename: {real_name}")
                FILE_NAME = real_name

            return True
    except Exception as e:
        print(f"  ZIP extraction error: {e}")
        return False


def cleanup_gas_folder(folder_id: str):
    """Delete a GAS temp folder."""
    try:
        requests.get(GAS_BRIDGE_URL, params={
            "action":   "cleanup_folder",
            "folderId": folder_id,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=30)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  ZIP Processing (flatten + filter + watermark)
# ─────────────────────────────────────────────

def should_exclude(entry_name: str) -> bool:
    """Check if a ZIP entry matches any exclude pattern."""
    basename = os.path.basename(entry_name)
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(basename, pattern) or fnmatch.fnmatch(entry_name, pattern):
            return True
    return False


def is_extractable_archive(filepath: str, original_name: str) -> bool:
    """Check if the downloaded file is a compressed archive that should be unpacked."""
    ext = os.path.splitext(original_name)[1].lower()
    if ext in STANDALONE_EXTENSIONS:
        return False
    if ext in EXTRACTABLE_EXTENSIONS:
        return True
    if zipfile.is_zipfile(filepath):
        return True
    try:
        res = subprocess.run(["7z", "l", filepath], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if res.returncode == 0:
            return True
    except Exception:
        pass
    return False


def flatten_staging_dir(staging_dir: str):
    """If all extracted items sit inside a single top-level folder, hoist them up to root."""
    while True:
        items = os.listdir(staging_dir)
        if len(items) == 1 and os.path.isdir(os.path.join(staging_dir, items[0])):
            sub = os.path.join(staging_dir, items[0])
            print(f"  Flattening single top-level directory: {items[0]}")
            for child in os.listdir(sub):
                shutil.move(os.path.join(sub, child), os.path.join(staging_dir, child))
            os.rmdir(sub)
        else:
            break


def filter_and_clean_staging(staging_dir: str) -> dict:
    """
    Recursively walk staging_dir bottom-up:
    - Delete excluded files and directories (SP Flash Tool, Drivers, *.url, etc.)
    - Count kept files and total size
    NOTE: Internal filenames are NEVER renamed. Only the outer ZIP name gets
    cleaned/branded. This prevents corruption of firmware component names
    like APDB_MT6761_S01__W2104 and Checksum.ini.
    """
    stats = {"kept": 0, "excluded": 0, "total_size": 0}

    for root, dirs, files in os.walk(staging_dir, topdown=False):
        # 1. Process files -- delete excluded, count the rest
        for fname in files:
            fpath = os.path.join(root, fname)
            rel_path = os.path.relpath(fpath, staging_dir).replace("\\", "/")

            if should_exclude(rel_path) or should_exclude(fname):
                try:
                    os.remove(fpath)
                    stats["excluded"] += 1
                    print(f"  Excluded file: {rel_path}")
                except OSError:
                    pass
                continue

            stats["kept"] += 1
            try:
                stats["total_size"] += os.path.getsize(fpath)
            except OSError:
                pass

        # 2. Process directories -- delete excluded
        for dname in dirs:
            dpath = os.path.join(root, dname)
            rel_dpath = os.path.relpath(dpath, staging_dir).replace("\\", "/")

            if should_exclude(rel_dpath) or should_exclude(dname):
                try:
                    shutil.rmtree(dpath, ignore_errors=True)
                    stats["excluded"] += 1
                    print(f"  Excluded directory: {rel_dpath}")
                except OSError:
                    pass
                continue

    return stats


def restructure_staging_for_packaging(staging_dir: str, add_branding: bool = True):
    """Move all firmware files into firmware/ subfolder.
    If a firmware/ folder already exists (case-insensitive), reuse it instead
    of creating a nested firmware/firmware/ structure.
    Optionally add branding files at root level (outside firmware/).
    """
    # Check if there's already a firmware/ directory (case-insensitive)
    existing_firmware = None
    for item in os.listdir(staging_dir):
        if item.lower() == "firmware" and os.path.isdir(os.path.join(staging_dir, item)):
            existing_firmware = item
            break

    if existing_firmware:
        # Already has a firmware folder -- normalize case if needed
        if existing_firmware != "firmware":
            old_path = os.path.join(staging_dir, existing_firmware)
            new_path = os.path.join(staging_dir, "firmware")
            os.rename(old_path, new_path)
            print(f"  Renamed existing {existing_firmware}/ -> firmware/")

        # Move any remaining root-level files INTO firmware/
        firmware_dir = os.path.join(staging_dir, "firmware")
        for item in os.listdir(staging_dir):
            if item.lower() == "firmware":
                continue
            src = os.path.join(staging_dir, item)
            dst = os.path.join(firmware_dir, item)
            shutil.move(src, dst)
        print("  Reused existing firmware/ folder")
    else:
        # No firmware folder -- create one and move everything in
        firmware_dir = os.path.join(staging_dir, "firmware")
        os.makedirs(firmware_dir, exist_ok=True)
        for item in os.listdir(staging_dir):
            if item == "firmware":
                continue
            src = os.path.join(staging_dir, item)
            dst = os.path.join(firmware_dir, item)
            shutil.move(src, dst)
        print("  Created firmware/ subfolder")

    if add_branding:
        _write_branding_files(staging_dir)


def _write_branding_files(target_dir: str):
    """Write all branding files (text + InternetShortcut) into target_dir."""
    readme_path = os.path.join(target_dir, "README - Download Info.txt")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(WATERMARK_README)

    brand_path = os.path.join(target_dir, f"Downloaded from {BRAND_NAME}.txt")
    with open(brand_path, "w", encoding="utf-8") as f:
        f.write(WATERMARK_BRAND)

    url_path = os.path.join(target_dir, f"{BRAND_NAME}.url")
    with open(url_path, "w", encoding="utf-8") as f:
        f.write(WATERMARK_URL)


def repack_staging_to_zip(staging_dir: str, output_zip_path: str, root_folder: str = ""):
    """Stream all files from staging_dir into a ZIP64 archive without high memory usage.
    If root_folder is set, all ZIP entry paths are prefixed with it to create
    a single top-level folder inside the ZIP.
    """
    CHUNK_SIZE = 64 * 1024 * 1024  # 64MB streaming buffer
    with zipfile.ZipFile(output_zip_path, "w", zipfile.ZIP_STORED, allowZip64=True) as out_zip:
        for root, _, files in os.walk(staging_dir):
            for fname in files:
                fpath = os.path.join(root, fname)
                rel_path = os.path.relpath(fpath, staging_dir).replace("\\", "/")
                if root_folder:
                    rel_path = f"{root_folder}/{rel_path}"
                with open(fpath, "rb") as src, \
                     out_zip.open(rel_path, "w", force_zip64=True) as dst:
                    while True:
                        chunk = src.read(CHUNK_SIZE)
                        if not chunk:
                            break
                        dst.write(chunk)


NESTED_ARCHIVE_EXTS = (".zip", ".7z", ".rar")
LOCKED_SHARE_LIMIT = 0.5   # refuse when over half the firmware, by size, is locked


def _archive_lock_state(path: str):
    """(locked_bytes, total_bytes) for one archive's members, read by `7z l -slt`.

    An empty password (-p) makes 7z answer instead of prompting. An archive
    whose file LIST is itself encrypted cannot be listed at all; that is
    reported as fully locked.
    """
    try:
        res = subprocess.run(["7z", "l", "-slt", "-p", path], stdin=subprocess.DEVNULL,
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=300)
    except Exception:
        return 0, 0
    out = res.stdout.decode("utf-8", errors="replace")
    err = res.stderr.decode("utf-8", errors="replace")
    if "Wrong password" in err or "Can not open encrypted archive" in err:
        size = os.path.getsize(path)
        return size, size
    locked = total = 0
    size, enc, folder = 0, False, False
    for line in out.splitlines() + [""]:
        if line.startswith("Size = "):
            try:
                size = int(line[7:].strip() or 0)
            except ValueError:
                size = 0
        elif line.startswith("Encrypted = "):
            enc = line.strip().endswith("+")
        elif line.startswith("Folder = "):
            folder = line.strip().endswith("+")
        elif line.strip() == "":
            if size and not folder:
                total += size
                if enc:
                    locked += size
            size, enc, folder = 0, False, False
    return locked, total


def find_password_locked(staging_dir: str) -> str:
    """A reason to refuse the build, or '' when the firmware is usable.

    Added 2026-09-24 after a real case. "Tecno Pouvoir 1 LA6 MT6580 7.0 Dead
    Recovery ... Factroy Signed Firmware" passed every check and was published:
    its outer archive is intact, but the firmware inside it is a second archive
    with 17 of 18 files password-protected, shipped beside a "Contact Me For
    Password" folder holding AnyDesk, UltraViewer and a stranger's email -- a
    pay-for-the-password package. Every download of it was unusable.

    Only archives INSIDE the extracted package are examined (an encrypted outer
    archive already fails extraction). Measured by bytes, so a small locked
    extra such as a tools archive does not reject real firmware beside it.
    """
    total_bytes = 0
    locked_bytes = 0
    worst = ""
    for root, _dirs, files in os.walk(staging_dir):
        for name in files:
            path = os.path.join(root, name)
            try:
                size = os.path.getsize(path)
            except OSError:
                continue
            total_bytes += size
            if not name.lower().endswith(NESTED_ARCHIVE_EXTS):
                continue
            inner_locked, inner_total = _archive_lock_state(path)
            if inner_total and inner_locked / inner_total > LOCKED_SHARE_LIMIT:
                locked_bytes += size
                if not worst:
                    worst = name
    if total_bytes and locked_bytes / total_bytes > LOCKED_SHARE_LIMIT:
        return ("Firmware is password-protected (%s): %d%% of the package is locked "
                "and cannot be flashed, so it was not uploaded."
                % (worst, round(100 * locked_bytes / total_bytes)))
    return ""


def process_archive(source_path: str, output_path: str, original_name: str,
                    root_folder: str = "", clean_output_path: str = "",
                    add_branding: bool = True) -> dict:
    """
    Extract archive (.rar, .7z, .zip, .tar), filter exclusions,
    restructure into firmware/ subfolder, optionally add brand text files,
    and repack into a clean ZIP archive.

    Internal filenames are NEVER modified -- only excluded files are removed.

    Args:
        source_path: Path to the downloaded archive
        output_path: Destination for the ZIP
        original_name: Original filename (for extraction fallback)
        root_folder: Top-level folder name inside the ZIP
        clean_output_path: If set, also build a clean (unbranded) ZIP here
        add_branding: Write the branding files into the archive. False under
            SERVE_TIME_BRANDING, where the Worker appends them per request and
            the stored payload must stay brand-neutral.
    """
    # ADDED 2026-09-24: a ZIP is repacked by copying its compressed bytes
    # (zip_passthrough.py) -- no 25% growth, no extraction, seconds not
    # minutes. Same files in the same places; anything it has not been proven
    # on falls through to the extract-and-store path below, unchanged.
    if not clean_output_path and zipfile.is_zipfile(source_path):
        report_progress("processing", 81, "Checking archive contents...", force=True)
        locked = find_password_locked_in_zip(source_path)
        if locked:
            raise RuntimeError(locked)
        extra = None
        if add_branding:
            extra = {"README - Download Info.txt": WATERMARK_README.encode("utf-8"),
                     f"Downloaded from {BRAND_NAME}.txt": WATERMARK_BRAND.encode("utf-8"),
                     f"{BRAND_NAME}.url": WATERMARK_URL.encode("utf-8")}
        try:
            report_progress("processing", 83, "Repacking without recompressing...", force=True)
            stats = zip_passthrough.passthrough_repack(source_path, output_path, EXCLUDE_PATTERNS,
                                                       root_folder=root_folder, extra_files=extra)
            print(f"  Direct copy: {stats['kept']} files kept, {stats['excluded']} excluded, "
                  f"{stats['total_size'] // (1024*1024)} MB")
            return stats
        except zip_passthrough.Decline as e:
            print(f"  Direct copy not used ({e}); extracting instead")

    report_progress("processing", 81, "Extracting archive contents...", force=True)
    staging_dir = tempfile.mkdtemp(prefix="pvl_stage_")

    try:
        # Extract using 7z (handles RAR, 7Z, ZIP, TAR, etc. uniformly)
        extracted = False
        try:
            res = subprocess.run(["7z", "x", "-y", f"-o{staging_dir}", source_path],
                                 stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            if res.returncode == 0:
                extracted = True
            else:
                err_output = res.stderr.decode("utf-8", errors="replace").strip() or res.stdout.decode("utf-8", errors="replace").strip()
                err_lines = [line.strip() for line in err_output.splitlines() if line.strip()]
                short_err = " | ".join(err_lines[-3:]) if err_lines else f"exit code {res.returncode}"
                print(f"  7z extraction returned code {res.returncode}: {short_err}")
        except FileNotFoundError:
            pass

        # Fallback to Python zipfile if 7z isn't available and it's a zip
        if not extracted and zipfile.is_zipfile(source_path):
            print("  Attempting extraction via Python zipfile fallback...")
            with zipfile.ZipFile(source_path, "r") as zf:
                zf.extractall(staging_dir)
            extracted = True

        if not extracted:
            raise RuntimeError(f"Could not extract archive {original_name}")

        # FIXED 2026-09-24: refuse firmware that is password-locked inside.
        locked = find_password_locked(staging_dir)
        if locked:
            raise RuntimeError(locked)

        # Flatten staging directory if there's a single top-level folder
        flatten_staging_dir(staging_dir)

        # Remove excluded files only -- NO renaming of internal filenames
        report_progress("processing", 83, "Removing exclusions...", force=True)
        stats = filter_and_clean_staging(staging_dir)

        # Move all files into firmware/ subfolder (no branding yet)
        restructure_staging_for_packaging(staging_dir, add_branding=False)

        # If dual-build is on, repack the clean version FIRST (firmware/ only)
        if clean_output_path:
            report_progress("processing", 84, "Packaging clean ZIP...", force=True)
            clean_folder = root_folder.replace(f" - {BRAND_NAME}", "")
            repack_staging_to_zip(staging_dir, clean_output_path, root_folder=clean_folder)
            print(f"  Clean ZIP built: {clean_folder}.zip")

        if add_branding:
            # Add branding files at root (outside firmware/)
            _write_branding_files(staging_dir)
            report_progress("processing", 84, "Packaging branded ZIP...", force=True)
        else:
            # Serve-time branding: nothing brand-specific goes in the archive.
            report_progress("processing", 84, "Packaging brand-neutral ZIP...", force=True)

        repack_staging_to_zip(staging_dir, output_path, root_folder=root_folder)

        print(f"  Processed archive: {stats['kept']} files kept, {stats['excluded']} excluded, "
              f"{stats['total_size'] // (1024*1024)} MB")
        return stats

    finally:
        shutil.rmtree(staging_dir, ignore_errors=True)


def find_password_locked_in_zip(zip_path: str) -> str:
    """find_password_locked(), for the passthrough: the same verdict, read
    from the central directory, extracting only the archives inside."""
    total_bytes = locked_bytes = 0
    worst = ""
    with zipfile.ZipFile(zip_path) as zf:
        infos = [i for i in zf.infolist() if not i.is_dir()]
        total_bytes = sum(i.file_size for i in infos)
        for info in infos:
            leaf = info.filename.replace("\\", "/").rsplit("/", 1)[-1]
            if not leaf.lower().endswith(NESTED_ARCHIVE_EXTS):
                continue
            tmp = tempfile.mkdtemp(prefix="pvl_nested_")
            try:
                path = os.path.join(tmp, "inner" + os.path.splitext(leaf)[1].lower())
                with zf.open(info) as src, open(path, "wb") as dst:
                    shutil.copyfileobj(src, dst, 16 * 1024 * 1024)
                inner_locked, inner_total = _archive_lock_state(path)
            finally:
                shutil.rmtree(tmp, ignore_errors=True)
            if inner_total and inner_locked / inner_total > LOCKED_SHARE_LIMIT:
                locked_bytes += info.file_size
                if not worst:
                    worst = leaf
    if total_bytes and locked_bytes / total_bytes > LOCKED_SHARE_LIMIT:
        return ("Firmware is password-protected (%s): %d%% of the package is locked "
                "and cannot be flashed, so it was not uploaded."
                % (worst, round(100 * locked_bytes / total_bytes)))
    return ""


def archive_entries(path: str) -> list:
    """The archive's file list as [{'name', 'size'}], or [] if it cannot be read.
    A zip is read from its central directory; anything else through 7z."""
    try:
        if zipfile.is_zipfile(path):
            with zipfile.ZipFile(path) as zf:
                return [{"name": i.filename, "size": i.file_size}
                        for i in zf.infolist() if not i.is_dir()]
        res = subprocess.run(["7z", "l", "-slt", "-p", path], stdin=subprocess.DEVNULL,
                             stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, timeout=300)
        out = res.stdout.decode("utf-8", errors="replace")
        cur, entries, started = {}, [], False
        for line in out.splitlines() + [""]:
            if line.startswith("----------"):
                started = True
                continue
            if not started:
                continue
            if line.startswith("Path = "):
                cur = {"name": line[7:]}
            elif line.startswith("Size = ") and cur:
                cur["size"] = int(line[7:].strip() or 0)
            elif line.startswith("Folder = +"):
                cur = {}
            elif not line.strip() and cur.get("name"):
                entries.append(cur)
                cur = {}
        return entries
    except Exception as e:
        print(f"  Could not list the archive ({e})")
        return []


def package_standalone_file(raw_path: str, output_path: str, original_name: str,
                           root_folder: str = "", add_branding: bool = True):
    """
    For disk images (.iso) and standalone binaries (.pac, .img, .bin):
    Place the intact file into firmware/ subfolder under its EXACT original name,
    along with the download branding text files at the root level.

    Structure: {root_folder}/firmware/{original_name}
               {root_folder}/README - Download Info.txt
               {root_folder}/Downloaded from lexzytechinc.com.txt
    """
    report_progress("processing", 82, "Packaging standalone file...", force=True)

    CHUNK_SIZE = 64 * 1024 * 1024
    firmware_prefix = f"{root_folder}/firmware" if root_folder else "firmware"
    root_prefix = root_folder if root_folder else ""

    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_STORED, allowZip64=True) as out_zip:
        # Write the firmware file into firmware/ subfolder with its original name
        inner_path = f"{firmware_prefix}/{original_name}"
        with open(raw_path, "rb") as src, \
             out_zip.open(inner_path, "w", force_zip64=True) as dst:
            while True:
                chunk = src.read(CHUNK_SIZE)
                if not chunk:
                    break
                dst.write(chunk)

        # Write branding files at root level (outside firmware/).
        # Skipped under SERVE_TIME_BRANDING -- the Worker appends them instead.
        if add_branding:
            brand_prefix = f"{root_prefix}/" if root_prefix else ""
            out_zip.writestr(f"{brand_prefix}Downloaded from {BRAND_NAME}.txt", WATERMARK_BRAND)
            out_zip.writestr(f"{brand_prefix}README - Download Info.txt", WATERMARK_README)
            out_zip.writestr(f"{brand_prefix}{BRAND_NAME}.url", WATERMARK_URL)

    print(f"  Packaged standalone file: {original_name} (unchanged name)")


# ─────────────────────────────────────────────
#  Hugging Face Upload
# ─────────────────────────────────────────────

def upload_to_hf(file_path: str, hf_filename: str) -> str:
    """Upload a file to the Hugging Face dataset repo. Returns the download URL."""
    report_progress("uploading", 88, "Uploading to permanent cache...", force=True)

    api = HfApi(token=HF_TOKEN)

    # Upload the file
    api.upload_file(
        path_or_fileobj=file_path,
        path_in_repo=hf_filename,
        repo_id=HF_REPO_ID,
        repo_type="dataset",
        commit_message=f"Cache: {hf_filename}",
    )

    # Construct the direct download URL
    hf_url = f"https://huggingface.co/datasets/{HF_REPO_ID}/resolve/main/{hf_filename}"
    print(f"  Uploaded to HF: [masked] ({FILE_ID})")
    return hf_url


# ─────────────────────────────────────────────
#  Main Pipeline
# ─────────────────────────────────────────────

def main():
    print("=" * 60)
    print(f"PVL Build Worker")
    print(f"  File ID:    {FILE_ID}")
    print(f"  Filename:   {FILE_NAME}")
    print(f"  Build ID:   {BUILD_ID}")
    print(f"  Excludes:   {len(EXCLUDE_PATTERNS)} patterns")
    print(f"  HF Repo:    [configured]")
    print(f"  Callback:   [configured]")
    print(f"  Dual Build: {DUAL_BUILD}")
    print("=" * 60)

    # Declared before the try so the failure handler can release a reservation
    # taken partway through.
    reserve_token = ""
    source_sha = ""
    verdict = {}

    start_heartbeat()

    work_dir = tempfile.mkdtemp(prefix="pvl_build_")
    raw_path = os.path.join(work_dir, "raw_download")
    processed_path = os.path.join(work_dir, "processed.zip")
    clean_path = os.path.join(work_dir, "clean.zip") if DUAL_BUILD else ""

    try:
        # ─── Step 1: Get file metadata ───
        is_mediafire = (SOURCE_TYPE == "mediafire") or FILE_ID.startswith("mf_") or ("mediafire.com" in (SOURCE_URL or ""))
        is_mega = (SOURCE_TYPE == "mega") or FILE_ID.startswith("mega_") or is_mega_url(SOURCE_URL or "")
        original_name = FILE_NAME

        if not is_mediafire and not is_mega:
            report_progress("metadata", 2, "Fetching file info...", force=True)
            try:
                meta = get_file_metadata(FILE_ID)
                meta_name = meta.get("name", "")
                if meta_name and not is_generic_filename(meta_name):
                    original_name = meta_name
                file_size = int(meta.get("size", 0))
                mime_type = meta.get("mimeType", "")
                print(f"  File: {original_name} ({file_size // (1024*1024)} MB, {mime_type})")
            except Exception as e:
                print(f"  Metadata fetch failed (non-fatal): {e}")

        # ─── Step 2: Download from Source ───
        report_progress("downloading", 5, "Starting download...", force=True)

        if not download_file(FILE_ID, raw_path):
            report_error("All download methods failed. File may be restricted or quota fully exhausted.")
            sys.exit(1)

        # Update original_name: if download recovered a non-generic filename (e.g. from MEGA or MediaFire Content-Disposition), adopt it!
        if FILE_NAME and not is_generic_filename(FILE_NAME):
            if is_generic_filename(original_name) or is_mega or is_mediafire:
                original_name = FILE_NAME

        # Fallback to URL path or FILE_ID if still generic
        if is_generic_filename(original_name):
            if FILE_NAME and not is_generic_filename(FILE_NAME):
                original_name = FILE_NAME
            elif SOURCE_URL:
                src_parts = [p for p in SOURCE_URL.split("?")[0].split("/") if p and p.lower() not in ("file", "view", "edit", "download")]
                if src_parts and "." in src_parts[-1] and not is_generic_filename(src_parts[-1]):
                    original_name = clean_watermarks(urllib.parse.unquote(src_parts[-1]))
            if is_generic_filename(original_name):
                original_name = f"{FILE_ID}.zip"

        raw_size = os.path.getsize(raw_path)
        report_progress("downloading", 80,
                        f"Download complete ({raw_size // (1024*1024)} MB)", force=True)

        # ─── Step 2b: SOURCE dedup, before anything expensive ───
        #
        # Deliberately here: after the download, before the repack. Hashing the
        # OUTPUT would be useless for the actual goal -- the repack writes
        # branding files with fresh timestamps and a source-derived folder
        # name, so the same firmware from two mirrors produces two different
        # output hashes. Only the raw source bytes are comparable across
        # mirrors.
        report_progress("dedup", 80, "Checking for an existing copy...", force=True)
        source_sha = dedup_client.sha256_file(raw_path)
        print(f"  Source SHA-256: {source_sha}")

        verdict = dedup_client.check(
            source_sha,
            size_bytes=raw_size,
            build_id=BUILD_ID,
            file_id=FILE_ID,
            source_url=SOURCE_URL,
            source_type=SOURCE_TYPE,
        )

        if verdict.get("duplicate"):
            # Already indexed from another mirror. No build, no upload, no HF
            # quota spent -- this is the saving the whole feature exists for.
            report_duplicate(verdict.get("file_id", ""), verdict.get("reason", ""))
            print("")
            print("=" * 60)
            print("BUILD SKIPPED -- source already indexed")
            print(f"  Existing file: {verdict.get('file_id')}")
            print("=" * 60)
            return

        if verdict.get("wait"):
            # Another build holds this exact source. Exiting non-zero lets the
            # retry queue pick it up after that build finishes or its
            # reservation expires; racing it would create the duplicate we are
            # trying to avoid.
            wait_for = verdict.get("retry_after", 60)
            report_error(f"Another build is already processing this file. Retry in ~{wait_for}s.")
            sys.exit(75)   # EX_TEMPFAIL

        reserve_token = verdict.get("reserve_token", "")
        if verdict.get("unchecked"):
            print(f"  Proceeding without a dedup check: {verdict.get('reason', '')}")

        # ─── Step 3: Compute branded name BEFORE processing ───
        # clean_watermarks() is ONLY applied to the outer archive name, never internal files
        cleaned_name = clean_watermarks(original_name)
        base_name = os.path.splitext(cleaned_name)[0]
        # Strip existing branding if present
        for strip in [" - lexzytechinc.com", " — lexzytechinc.com", "- lexzytechinc.com", "— lexzytechinc.com", "lexzytechinc.com"]:
            base_name = base_name.replace(strip, "").strip()
        # ADDED 2026-09-24: the name from NAMING-PLAN.md -- the vendor's own
        # string, unchanged, with brand/series/model in front and the chipset
        # behind, each only when missing and only from a trusted source (the
        # archive itself counts highest). Identity keys stay on the vendor
        # string (key_name), so the added detail never splits a duplicate.
        facts = None
        if is_extractable_archive(raw_path, original_name):
            entries = archive_entries(raw_path)
            if entries:
                try:
                    facts = payload_reader.read_payload(entries)
                except Exception as e:
                    print(f"  Payload read failed (non-fatal): {e}")
        root_base = ""
        if facts and facts.get("archive_root_name"):
            root_base = os.path.splitext(clean_watermarks(facts["archive_root_name"] + ".zip"))[0]
        samsung_code = ""
        if facts and facts.get("container") == "samsung_odin":
            samsung_code = name_composer.samsung_build_code([e["name"] for e in entries])
        vendor = name_composer.vendor_base("" if is_generic_filename(base_name) else base_name, root_base,
                                           samsung_code)
        key_name = f"{vendor}.zip" if vendor else ""
        composed, decisions = name_composer.stored_base_name(
            vendor, name_composer.parse_device_info(DEVICE_INFO), facts)
        for field, d in decisions.items():
            if d.get("status") != "omitted":
                print(f"  Name {field}: {d['status']} ({d['why']})")
        base_name = composed or vendor or base_name
        if is_generic_filename(base_name):
            base_name = FILE_ID
        branded_name = f"{base_name} - {BRAND_NAME}.zip"

        # The name the artifact is STORED under, and the top-level folder inside it.
        #
        # Under serve-time branding both must be brand-neutral. The brand used to
        # be baked into every ZIP entry path via root_folder, which would make the
        # payload prefix differ per brand and defeat the whole scheme -- the Worker
        # can only append to bytes that are shared across brands.
        if SERVE_TIME_BRANDING:
            stored_name = f"{base_name}.zip"
        else:
            stored_name = branded_name
        root_folder = os.path.splitext(stored_name)[0]  # folder name = zip name minus .zip

        print(f"  Original name: {original_name}")
        print(f"  Cleaned name:  {cleaned_name}")
        print(f"  Stored name:   {stored_name}")
        if SERVE_TIME_BRANDING:
            print(f"  Branding:      serve-time (Worker appends; archive stays neutral)")
        else:
            print(f"  Branded name:  {branded_name}")

        # ─── Step 4: Process the File ───
        if is_extractable_archive(raw_path, original_name):
            stats = process_archive(raw_path, processed_path, original_name,
                                    root_folder=root_folder,
                                    clean_output_path=clean_path if DUAL_BUILD else "",
                                    add_branding=not SERVE_TIME_BRANDING)
        else:
            package_standalone_file(raw_path, processed_path, original_name,
                                   root_folder=root_folder,
                                   add_branding=not SERVE_TIME_BRANDING)

        processed_size = os.path.getsize(processed_path)
        report_progress("processing", 85,
                        f"Processing complete ({processed_size // (1024*1024)} MB)", force=True)

        # Sanity check: a ZIP with only watermarks and no real content is ~3-4KB.
        if processed_size < 10240:
            report_error(f"Processed ZIP is only {processed_size} bytes -- source download was likely corrupt or empty. Aborting.")
            sys.exit(1)

        # ─── Step 5: Upload to Hugging Face ───
        hf_filename = f"{FILE_ID}/{stored_name}"
        hf_url = upload_to_hf(processed_path, hf_filename)

        # If dual build, upload the clean version too
        hf_url_clean = ""
        clean_size = 0
        if SERVE_TIME_BRANDING:
            # One artifact serves both variants: it IS the clean one, and the
            # Worker derives the branded stream from it. Reporting it as both
            # lets pvl_hf_masked_url() resolve either variant to these bytes.
            hf_url_clean = hf_url
            clean_size = processed_size
        elif DUAL_BUILD and clean_path and os.path.exists(clean_path):
            clean_hf_name = f"{FILE_ID}/{base_name}.zip"
            clean_size = os.path.getsize(clean_path)
            hf_url_clean = upload_to_hf(clean_path, clean_hf_name)
            print(f"  Clean version uploaded ({FILE_ID}, {clean_size} bytes)")

        # ─── Step 5b: Confirm the reservation ───
        #
        # Stage 2 (output dedup): the artifact hash is cheap insurance against
        # re-runs and re-uploads. Stage 1 above is what actually solves the
        # cross-mirror problem.
        content_sha = dedup_client.sha256_file(processed_path)
        print(f"  Content SHA-256: {content_sha}")

        if reserve_token:
            confirmation = dedup_client.confirm(source_sha, reserve_token, FILE_ID, content_sha)
            twin = confirmation.get("content_duplicate_of")
            if twin:
                print(f"  Note: identical artifact already stored as {twin}")
        elif verdict.get("unchecked"):
            # We uploaded without a check. Record it so it can be reconciled
            # rather than accumulating invisibly.
            dedup_client.record_unchecked(FILE_ID, source_sha, verdict.get("reason", ""))

        # ─── Step 6: Report completion ───
        report_complete(hf_url, processed_size, hf_url_clean, clean_size, key_name=key_name)

        print("\n" + "=" * 60)
        print("BUILD SUCCESSFUL")
        print(f"  HF URL: [masked]")
        print(f"  Size:   {processed_size // (1024*1024)} MB")
        if DUAL_BUILD and hf_url_clean:
            print(f"  Clean:  [masked]")
        print("=" * 60)

    except SystemExit:
        raise
    except Exception as e:
        traceback.print_exc()
        # Hand the hash back before giving up, or a crashed build blocks it for
        # the full reservation TTL and an immediate retry is told to wait.
        try:
            if reserve_token:
                dedup_client.release(source_sha, reserve_token)
        except Exception:
            pass
        report_error(f"Build failed: {str(e)}")
        sys.exit(1)
    finally:
        # Cleanup temp files
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
