#!/usr/bin/env python3
"""
PVL Build Worker — Downloads from Google Drive, processes ZIP, uploads to Hugging Face.

Runs on GitHub Actions. Reads all config from environment variables.
Posts real-time progress updates back to WordPress.

Environment variables (set by GitHub Actions):
  SA_CREDENTIALS_PATH   — Path to Service Account JSON
  GAS_BRIDGE_URL        — Google Apps Script bridge URL
  GAS_BRIDGE_SECRET     — GAS bridge shared secret
  HF_TOKEN              — Hugging Face write token
  HF_REPO_ID            — HF dataset repo (e.g. adminlexzytech/phone-firmware)
  BUILD_CALLBACK_SECRET — Shared secret for progress updates
  FILE_ID               — Google Drive file ID to download
  FILE_NAME             — Original filename
  CALLBACK_URL          — WordPress AJAX URL for progress reports
  BUILD_ID              — Unique build identifier
  EXCLUDE_PATTERNS      — Newline-separated glob patterns to exclude
"""

import os
import sys
import json
import time
import shutil
import hashlib
import zipfile
import fnmatch
import tempfile
import traceback
import subprocess
import urllib.parse
from pathlib import Path
from datetime import datetime, timezone

import jwt       # PyJWT
import requests
from huggingface_hub import HfApi

# ─────────────────────────────────────────────
#  Configuration
# ─────────────────────────────────────────────

SA_CREDENTIALS_PATH = os.environ.get("SA_CREDENTIALS_PATH", "")
GAS_BRIDGE_URL      = os.environ.get("GAS_BRIDGE_URL", "")
GAS_BRIDGE_SECRET   = os.environ.get("GAS_BRIDGE_SECRET", "")
HF_TOKEN            = os.environ.get("HF_TOKEN", "")
HF_REPO_ID          = os.environ.get("HF_REPO_ID", "adminlexzytech/phone-firmware")
CALLBACK_SECRET     = os.environ.get("BUILD_CALLBACK_SECRET") or os.environ.get("CALLBACK_SECRET", "")
FILE_ID             = os.environ.get("FILE_ID", "")
FILE_NAME           = os.environ.get("FILE_NAME", "")
CALLBACK_URL        = os.environ.get("CALLBACK_URL", "")
BUILD_ID            = os.environ.get("BUILD_ID", "")
EXCLUDE_PATTERNS    = [p.strip() for p in os.environ.get("EXCLUDE_PATTERNS", "").split("\n") if p.strip()]
SOURCE_TYPE         = os.environ.get("SOURCE_TYPE", "gdrive").strip().lower()
SOURCE_URL          = os.environ.get("SOURCE_URL", "").strip()

DRIVE_API_BASE   = "https://www.googleapis.com/drive/v3"
DRIVE_UPLOAD_BASE = "https://www.googleapis.com/upload/drive/v3"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"

BRAND_NAME  = "lexzytechinc.com"
BRAND_DOMAIN = "https://lexzytechinc.com"

WATERMARK_BRAND = (
    "╔═══════════════════════════════════════════════════════╗\n"
    "║                                                       ║\n"
    "║          Downloaded from LexzyTechInc.com              ║\n"
    "║                                                       ║\n"
    "║   This file was downloaded by a verified member of     ║\n"
    "║   LexzyTechInc.com. Redistribution without written     ║\n"
    "║   permission is strictly prohibited.                   ║\n"
    "║                                                       ║\n"
    "║   Website:   https://lexzytechinc.com                  ║\n"
    "║   YouTube:   https://youtube.com/@lexzytech             ║\n"
    "║   Telegram:  https://t.me/LexzyTechinc                 ║\n"
    "║   Facebook:  https://facebook.com/LexzyTech            ║\n"
    "║                                                       ║\n"
    "║   Thank you for supporting our platform!               ║\n"
    "╚═══════════════════════════════════════════════════════╝\n"
)

WATERMARK_README = (
    "================================================================\n"
    "   DOWNLOAD INFORMATION — LexzyTechInc.com\n"
    "================================================================\n\n"
    "This archive was generated by the LexzyTechInc.com\n"
    "download system.\n\n"
    "Source:      LexzyTechInc.com (Members Area)\n"
    "Usage:       Personal use only — do not redistribute\n"
    f"Generated:   {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Need Help?\n"
    "────────────────────────────────────────────────────────\n"
    "  Email:     support@lexzytechinc.com\n"
    "  Website:   https://lexzytechinc.com\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Upgrade to VIP\n"
    "────────────────────────────────────────────────────────\n"
    "  Instant downloads, no daily limits, priority support.\n"
    "  https://lexzytechinc.com/upgrade\n\n"
    "© LexzyTechInc.com — All Rights Reserved\n"
)


# ─────────────────────────────────────────────
#  Watermark Cleaning (ported from core.firmware.php → firmware_clean_filename)
# ─────────────────────────────────────────────

import re as _re

def is_generic_filename(name: str) -> bool:
    """Check if a filename is a generic placeholder, file ID, or hash."""
    if not name:
        return True
    clean = str(name).strip()
    clean_lower = clean.lower()

    # 1. Check exact generic words
    if clean_lower in ("download", "download.zip", "file", "file.zip", "raw_download", "raw_download.zip", "archive", "document", "none", "null"):
        return True

    # 2. Check if name matches FILE_ID or is an ID prefix
    if FILE_ID and (clean == FILE_ID or clean_lower == FILE_ID.lower() or clean_lower == f"{FILE_ID.lower()}.zip"):
        return True
    if clean_lower.startswith("mf_") or clean_lower.startswith("pvl_"):
        return True

    # 3. Strip extension and check base name
    base = os.path.splitext(clean_lower)[0]
    if base in ("download", "file", "raw_download", "archive", "document", "none", "null"):
        return True
    if FILE_ID and base == FILE_ID.lower():
        return True

    # 4. If base has no dots, no spaces, and looks like a raw Google Drive ID or hash (25-50 chars)
    if "." not in clean and _re.match(r'^[a-zA-Z0-9_-]{25,50}$', clean):
        return True

    return False

def clean_watermarks(filename: str) -> str:
    """Strip third-party site watermarks from firmware filenames and archive entries.
    Mirrors firmware_clean_filename() from core.firmware.php.
    """
    if not filename:
        return ""
    c = filename

    # 1. Bracket watermarks at start: [up_addROM.com]_, [Hovatek], [NaijaROM], [FirmwareFile], etc.
    c = _re.sub(r'^\[[^\]]+\]\s*_?', '', c)

    # 2. _[HardReset.info] or similar anywhere
    c = _re.sub(r'_?\[[^\]]+\]', '', c)

    # 3. Leading site domain prefix: "up_addROM.com_", "www.site.com-", "site.com_", etc.
    c = _re.sub(r'^(?:up_)?(?:www\.)?[a-zA-Z0-9]+\.(?:com|net|org|co|in|info|io|xyz|biz)[_\s-]+', '', c, flags=_re.I)

    # 4. _by_(FirmwareOS.com) -- specific pattern BEFORE general parens removal
    c = _re.sub(r'_?by_?\(?[a-zA-Z0-9_-]+(?:\.[a-zA-Z]{2,6})?\)?', '', c, flags=_re.I)

    # 5. Site names in parentheses: (MobiFirmware.com), (by_NaijaROM.Com), (firmwarefile.com), etc.
    c = _re.sub(r'\([^)]*\.(?:com|net|org|io|co|in|info|xyz|biz)[^)]*\)', '', c, flags=_re.I)

    # 6. Parenthesized by-watermarks even without .com: _(by_SiteName), _(by_NaijaROM), _(by_)
    c = _re.sub(r'_?\(by[_\s][^)]*\)', '', c, flags=_re.I)

    # 7. Standalone site name references in filenames
    c = _re.sub(r'[\s_-]*(?:addROM|TecnoFirmware|NaijaROM|FirmwareFile|MobiFirmware|XDAFirmware|Firmware4mobile|Firmware4mobiles|Repairmymobile|RepairMyMobile|FirmwareOS|HardReset|MobileGuru4|Rom2box|Samfw|EasyFirmware)\.(?:com|net|org|co|in|info|io|xyz)[\s_-]*', '_', c, flags=_re.I)

    # 8. _by_AnySiteName before extension
    c = _re.sub(r'_by_[a-zA-Z0-9_\.]+(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 9. _Repairmymobile / _ RepairMyMobile.in suffix before extension
    c = _re.sub(r'[\s_-]+Repairmymobile(?:\.(?:co|in))?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 10. _RMM suffix (RepairMyMobile abbreviation)
    c = _re.sub(r'_?RMM(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 11. _Firmware4mobile suffix before extension
    c = _re.sub(r'_?Firmware4mobiles?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 12. _MobileGuru4.com / _MobileGuru4 suffix before extension
    c = _re.sub(r'_?MobileGuru4(?:\.com)?(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 13. Catch-all: trailing _by or _by_ before extension
    c = _re.sub(r'[_\s-]+by[_\s]*(?=\.(?:zip|rar|7z|pac|tar|gz|iso|bin|img)$)', '', c, flags=_re.I)

    # 14. Cleanup: double underscores/dashes
    c = _re.sub(r'_{2,}', '_', c)
    c = _re.sub(r'-{2,}', '-', c)

    # 15. Trailing underscore/dash before extension
    c = _re.sub(r'[_-]+\.(?=zip|rar|7z|pac|tar|gz|iso|bin|img)', '.', c, flags=_re.I)

    # 16. Leading underscore/dash
    c = _re.sub(r'^[_-]+', '', c)

    return c.strip()


# ─────────────────────────────────────────────
#  Progress Reporting
# ─────────────────────────────────────────────

_last_progress_time = 0

def report_progress(stage: str, percent: int, message: str = "", force: bool = False):
    """Post a progress update to WordPress. Throttled to every 15 seconds unless forced."""
    global _last_progress_time
    now = time.time()
    if not force and (now - _last_progress_time) < 15:
        return
    _last_progress_time = now

    print(f"[{percent}%] {stage}: {message}")

    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    stage,
            "percent":  min(percent, 100),
            "message":  message,
        }, timeout=10)
    except Exception as e:
        print(f"  Warning: progress callback failed: {e}")


def report_error(message: str):
    """Report a fatal error to WordPress."""
    print(f"[ERROR] {message}")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "error",
            "percent":  0,
            "message":  message,
        }, timeout=10)
    except Exception:
        pass


def report_complete(hf_url: str, file_size: int):
    """Report successful completion to WordPress."""
    print(f"[100%] Complete: {hf_url} ({file_size} bytes)")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "complete",
            "percent":  100,
            "message":  "Build complete",
            "hf_url":   hf_url,
            "hf_size":  file_size,
        }, timeout=10)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  Google Drive Authentication (Service Account)
# ─────────────────────────────────────────────

_cached_token = None
_token_expiry = 0

def get_access_token() -> str:
    """Get a Google OAuth2 access token using the Service Account."""
    global _cached_token, _token_expiry

    if _cached_token and time.time() < _token_expiry:
        return _cached_token

    with open(SA_CREDENTIALS_PATH, "r") as f:
        creds = json.load(f)

    now = int(time.time())
    payload = {
        "iss":   creds["client_email"],
        "scope": "https://www.googleapis.com/auth/drive",
        "aud":   GOOGLE_TOKEN_URL,
        "iat":   now,
        "exp":   now + 3600,
    }

    token = jwt.encode(payload, creds["private_key"], algorithm="RS256")
    resp = requests.post(GOOGLE_TOKEN_URL, data={
        "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "assertion":  token,
    }, timeout=30)
    resp.raise_for_status()
    data = resp.json()

    _cached_token = data["access_token"]
    _token_expiry = now + data.get("expires_in", 3600) - 60
    return _cached_token


# ─────────────────────────────────────────────
#  Google Drive File Metadata
# ─────────────────────────────────────────────

def get_file_metadata(file_id: str) -> dict:
    """Fetch file metadata from Google Drive."""
    token = get_access_token()
    resp = requests.get(f"{DRIVE_API_BASE}/files/{file_id}", params={
        "fields": "id,name,mimeType,size",
        "supportsAllDrives": "true",
    }, headers={"Authorization": f"Bearer {token}"}, timeout=30)
    resp.raise_for_status()
    return resp.json()


# ─────────────────────────────────────────────
#  Download Cascade (mirrors PHP pvl_sa_download_to_temp)
# ─────────────────────────────────────────────

def download_file(file_id: str, dest_path: str) -> bool:
    """
    Download a file from storage source (Google Drive or MediaFire).
    """
    is_mediafire = (SOURCE_TYPE == "mediafire") or file_id.startswith("mf_") or ("mediafire.com" in SOURCE_URL)
    if is_mediafire:
        report_progress("downloading", 10, "Connecting to MediaFire source...", force=True)
        return mediafire_download(file_id, dest_path)

    # ─── Google Drive Cascade ───
    # ─── Approach 1A: GAS Copy ───
    report_progress("downloading", 5, "Trying GAS copy...", force=True)
    if gas_try_copy(file_id, dest_path):
        return True

    # ─── Approach 1B: GAS Folder + Signed URL ───
    report_progress("downloading", 10, "Trying GAS folder download...")
    if gas_try_folder_download(file_id, dest_path):
        return True

    # ─── Approach 2: Web download URL ───
    report_progress("downloading", 15, "Trying web download URL...")
    if web_download(file_id, dest_path):
        return True

    # ─── Approach 3: Standard API ───
    report_progress("downloading", 20, "Trying API download...")
    if api_download(file_id, dest_path):
        return True

    return False


def mediafire_download(file_id: str, dest_path: str) -> bool:
    """Download a file from MediaFire by resolving direct link from public page."""
    global FILE_NAME
    import re

    quickkey = file_id.replace("mf_", "").strip()
    page_url = SOURCE_URL if (SOURCE_URL and "mediafire.com" in SOURCE_URL) else f"https://www.mediafire.com/file/{quickkey}"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    }

    try:
        session = requests.Session()
        resp = session.get(page_url, headers=headers, timeout=30)
        if resp.status_code != 200:
            print(f"  MediaFire page returned HTTP {resp.status_code}")
            return False

        html = resp.text

        # Extract direct download link
        direct_url = None
        m = re.search(r'href=["\'](https?://download\d+\.mediafire\.com/[^"\']+)["\']', html, re.I)
        if m:
            direct_url = m.group(1)
        else:
            m = re.search(r'id=["\']downloadButton["\'][^>]*href=["\']([^"\']+)["\']', html, re.I)
            if m:
                direct_url = m.group(1)
            else:
                m = re.search(r'aria-label=["\']Download file["\'][^>]*href=["\']([^"\']+)["\']', html, re.I)
                if m:
                    direct_url = m.group(1)
                else:
                    m = re.search(r'https?://(?:www\.)?mediafire\.com/file_download/[^\s"\'<>]+', html, re.I)
                    if m:
                        direct_url = m.group(0)

        if not direct_url:
            print(f"  Could not extract direct download URL from MediaFire page: {page_url}")
            return False

        # Extract original filename from MediaFire HTML, direct URL, or SOURCE_URL
        scraped_fn = None
        fn_match = re.search(r'<div[^>]+class=["\'][^"\']*(?:file-name|filename)[^"\']*["\'][^>]*>([^<]+)</div>', html, re.I)
        if fn_match:
            scraped_fn = fn_match.group(1).strip()
        
        if not scraped_fn and direct_url:
            url_fn = direct_url.split("/")[-1].split("?")[0]
            if url_fn:
                scraped_fn = urllib.parse.unquote(url_fn)

        if not scraped_fn and SOURCE_URL:
            src_parts = [p for p in SOURCE_URL.split("?")[0].split("/") if p and p.lower() != "file"]
            if src_parts and "." in src_parts[-1]:
                scraped_fn = urllib.parse.unquote(src_parts[-1])

        if scraped_fn:
            scraped_clean = clean_watermarks(scraped_fn)
            if is_generic_filename(FILE_NAME) or ("." in scraped_clean and "." not in FILE_NAME):
                FILE_NAME = scraped_clean
                print(f"  Scraped MediaFire filename: {FILE_NAME}")

        print(f"  MediaFire direct download link found: {direct_url}")
        report_progress("downloading", 20, f"Downloading from MediaFire ({FILE_NAME})...")

        dl_resp = session.get(direct_url, headers=headers, stream=True, timeout=60)
        if dl_resp.status_code != 200:
            print(f"  MediaFire stream returned HTTP {dl_resp.status_code}")
            return False

        # Check Content-Disposition for filename
        cd = dl_resp.headers.get("Content-Disposition", "")
        if "filename=" in cd:
            cd_fn = re.search(r'filename=["\']?([^"\';]+)', cd)
            if cd_fn:
                cd_name = clean_watermarks(cd_fn.group(1).strip())
                if is_generic_filename(FILE_NAME) or ("." in cd_name and "." not in FILE_NAME):
                    FILE_NAME = cd_name
                    print(f"  Content-Disposition filename: {FILE_NAME}")

        total = int(dl_resp.headers.get("Content-Length", 0))
        downloaded = 0

        with open(dest_path, "wb") as f:
            for chunk in dl_resp.iter_content(chunk_size=65536):
                f.write(chunk)
                downloaded += len(chunk)
                if total > 0:
                    pct = int((downloaded / total) * 60) + 20
                    report_progress("downloading", pct,
                                    f"Downloaded {downloaded // (1024*1024)} / {total // (1024*1024)} MB")

        if os.path.getsize(dest_path) < 100:
            print("  MediaFire downloaded file is too small (<100 bytes)")
            return False

        print(f"  MediaFire download successful: {os.path.getsize(dest_path)} bytes")
        return True

    except Exception as e:
        print(f"  MediaFire download exception: {e}")
        traceback.print_exc()
        return False


def gas_try_copy(file_id: str, dest_path: str) -> bool:
    """GAS Approach A: Server-side copy with fresh quota."""
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action": "copy",
            "fileId": file_id,
            "secret": GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        if not data.get("success"):
            print(f"  GAS copy failed: {data.get('error', 'unknown')}")
            return False

        copy_id = data["copyId"]
        download_url = data["downloadUrl"]
        print(f"  GAS copy created: {copy_id}")

        # Download the copy
        success = stream_download(download_url, dest_path, auth=None)

        # Cleanup the copy
        try:
            requests.get(GAS_BRIDGE_URL, params={
                "action": "cleanup",
                "copyId": copy_id,
                "secret": GAS_BRIDGE_SECRET,
            }, timeout=30)
        except Exception:
            pass

        return success

    except Exception as e:
        print(f"  GAS copy error: {e}")
        return False


def gas_try_folder_download(file_id: str, dest_path: str) -> bool:
    """GAS Approach B: Folder + shortcut + signed URL."""
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action":   "folder_download",
            "fileId":   file_id,
            "fileName": FILE_NAME,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        if not data.get("success"):
            print(f"  GAS folder failed: {data.get('error', 'unknown')}")
            return False

        folder_id  = data["folderId"]
        signed_url = data["signedUrl"]
        print(f"  GAS folder created: {folder_id}, got signed URL")

        # Download the folder ZIP
        zip_path = dest_path + ".folder.zip"
        if not stream_download(signed_url, zip_path, auth=None):
            cleanup_gas_folder(folder_id)
            return False

        # Extract target file from the folder ZIP
        success = extract_from_google_zip(zip_path, dest_path)
        os.unlink(zip_path)
        cleanup_gas_folder(folder_id)
        return success

    except Exception as e:
        print(f"  GAS folder error: {e}")
        return False


def web_download(file_id: str, dest_path: str) -> bool:
    """Approach 2: Web download URL with SA Bearer token."""
    try:
        token = get_access_token()
        url = f"https://drive.usercontent.google.com/download?id={file_id}&export=download&confirm=t"
        return stream_download(url, dest_path, auth=f"Bearer {token}")
    except Exception as e:
        print(f"  Web download error: {e}")
        return False


def api_download(file_id: str, dest_path: str) -> bool:
    """Approach 3: Standard Google Drive API download."""
    try:
        token = get_access_token()
        url = f"{DRIVE_API_BASE}/files/{file_id}"
        return stream_download(url, dest_path, auth=f"Bearer {token}",
                               params={"alt": "media", "supportsAllDrives": "true"})
    except Exception as e:
        print(f"  API download error: {e}")
        return False


def stream_download(url: str, dest_path: str, auth: str = None, params: dict = None) -> bool:
    """Stream a URL to a local file. Reports progress during download."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
    if auth:
        headers["Authorization"] = auth

    resp = requests.get(url, headers=headers, params=params, stream=True, timeout=30, allow_redirects=True)

    # Reject obvious HTML error pages (Google returns 200 + text/html for quota errors)
    content_type = resp.headers.get("Content-Type", "")
    if "text/html" in content_type:
        snippet = resp.content[:500].decode("utf-8", errors="replace")
        print(f"  Download returned HTML: {snippet[:200]}")
        return False

    total = int(resp.headers.get("Content-Length", 0))
    downloaded = 0

    with open(dest_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=65536):
            f.write(chunk)
            downloaded += len(chunk)
            if total > 0:
                pct = int((downloaded / total) * 60) + 20  # 20-80% range
                report_progress("downloading", pct,
                                f"Downloaded {downloaded // (1024*1024)} / {total // (1024*1024)} MB")

    size = os.path.getsize(dest_path)

    # Check if it's actually HTML despite the Content-Type header lying
    with open(dest_path, "rb") as f:
        head = f.read(256)
    if b"<!DOCTYPE" in head or b"<html" in head or b"Quota exceeded" in head:
        snippet = head[:200].decode("utf-8", errors="replace")
        print(f"  Download is HTML despite Content-Type ({content_type}): {snippet[:150]}")
        os.unlink(dest_path)
        return False

    # Reject suspiciously small files (any real firmware ZIP is at least several MB)
    if size < 1024:
        print(f"  Download too small: {size} bytes (expected a real file, not an error page)")
        os.unlink(dest_path)
        return False

    print(f"  Downloaded {size:,} bytes")
    return True


def extract_from_google_zip(zip_path: str, dest_path: str) -> bool:
    """Extract the largest non-directory file from a Google folder ZIP."""
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            target = None
            target_size = 0
            for info in zf.infolist():
                if info.is_dir() or info.filename.startswith("."):
                    continue
                if info.file_size > target_size:
                    target = info
                    target_size = info.file_size

            if not target:
                print("  No files found in folder ZIP")
                return False

            with zf.open(target) as src, open(dest_path, "wb") as dst:
                shutil.copyfileobj(src, dst)

            print(f"  Extracted: {target.filename} ({target_size:,} bytes)")
            return True
    except Exception as e:
        print(f"  ZIP extraction error: {e}")
        return False


def cleanup_gas_folder(folder_id: str):
    """Delete a GAS temp folder."""
    try:
        requests.get(GAS_BRIDGE_URL, params={
            "action":   "cleanup_folder",
            "folderId": folder_id,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=30)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  ZIP Processing (flatten + filter + watermark)
# ─────────────────────────────────────────────

def should_exclude(entry_name: str) -> bool:
    """Check if a ZIP entry matches any exclude pattern."""
    basename = os.path.basename(entry_name)
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(basename, pattern) or fnmatch.fnmatch(entry_name, pattern):
            return True
    return False


EXTRACTABLE_EXTENSIONS = {'.zip', '.rar', '.7z', '.tar', '.gz', '.tgz', '.bz2', '.xz'}
STANDALONE_EXTENSIONS  = {'.iso', '.img', '.pac', '.bin', '.exe', '.tar.md5'}

def is_extractable_archive(filepath: str, original_name: str) -> bool:
    """Check if the downloaded file is a compressed archive that should be unpacked."""
    ext = os.path.splitext(original_name)[1].lower()
    if ext in STANDALONE_EXTENSIONS:
        return False
    if ext in EXTRACTABLE_EXTENSIONS:
        return True
    if zipfile.is_zipfile(filepath):
        return True
    try:
        res = subprocess.run(["7z", "l", filepath], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if res.returncode == 0:
            return True
    except Exception:
        pass
    return False


def flatten_staging_dir(staging_dir: str):
    """If all extracted items sit inside a single top-level folder, hoist them up to root."""
    while True:
        items = os.listdir(staging_dir)
        if len(items) == 1 and os.path.isdir(os.path.join(staging_dir, items[0])):
            sub = os.path.join(staging_dir, items[0])
            print(f"  Flattening single top-level directory: {items[0]}")
            for child in os.listdir(sub):
                shutil.move(os.path.join(sub, child), os.path.join(staging_dir, child))
            os.rmdir(sub)
        else:
            break


def filter_and_clean_staging(staging_dir: str) -> dict:
    """
    Recursively walk staging_dir bottom-up:
    - Delete excluded files and directories (SP Flash Tool, Drivers, *.url, etc.)
    - Clean third-party watermarks from all filenames and directory names
    """
    stats = {"kept": 0, "excluded": 0, "total_size": 0}

    for root, dirs, files in os.walk(staging_dir, topdown=False):
        # 1. Process files
        for fname in files:
            fpath = os.path.join(root, fname)
            rel_path = os.path.relpath(fpath, staging_dir).replace("\\", "/")

            if should_exclude(rel_path) or should_exclude(fname):
                try:
                    os.remove(fpath)
                    stats["excluded"] += 1
                    print(f"  Excluded file: {rel_path}")
                except OSError:
                    pass
                continue

            # Clean watermark from filename
            clean_fname = clean_watermarks(fname)
            if clean_fname and clean_fname != fname:
                clean_fpath = os.path.join(root, clean_fname)
                try:
                    os.rename(fpath, clean_fpath)
                    fpath = clean_fpath
                    print(f"  Renamed file: {fname} -> {clean_fname}")
                except OSError:
                    pass

            stats["kept"] += 1
            try:
                stats["total_size"] += os.path.getsize(fpath)
            except OSError:
                pass

        # 2. Process directories
        for dname in dirs:
            dpath = os.path.join(root, dname)
            rel_dpath = os.path.relpath(dpath, staging_dir).replace("\\", "/")

            if should_exclude(rel_dpath) or should_exclude(dname):
                try:
                    shutil.rmtree(dpath, ignore_errors=True)
                    stats["excluded"] += 1
                    print(f"  Excluded directory: {rel_dpath}")
                except OSError:
                    pass
                continue

            # Clean watermark from directory name
            clean_dname = clean_watermarks(dname)
            if clean_dname and clean_dname != dname:
                clean_dpath = os.path.join(root, clean_dname)
                try:
                    os.rename(dpath, clean_dpath)
                    print(f"  Renamed directory: {dname} -> {clean_dname}")
                except OSError:
                    pass

    return stats


def repack_staging_to_zip(staging_dir: str, output_zip_path: str):
    """Stream all files from staging_dir into a ZIP64 archive without high memory usage."""
    CHUNK_SIZE = 64 * 1024 * 1024  # 64MB streaming buffer
    with zipfile.ZipFile(output_zip_path, "w", zipfile.ZIP_STORED, allowZip64=True) as out_zip:
        for root, _, files in os.walk(staging_dir):
            for fname in files:
                fpath = os.path.join(root, fname)
                rel_path = os.path.relpath(fpath, staging_dir).replace("\\", "/")
                with open(fpath, "rb") as src, \
                     out_zip.open(rel_path, "w", force_zip64=True) as dst:
                    while True:
                        chunk = src.read(CHUNK_SIZE)
                        if not chunk:
                            break
                        dst.write(chunk)


def process_archive(source_path: str, output_path: str, original_name: str) -> dict:
    """
    Extract archive (.rar, .7z, .zip, .tar), filter exclusions,
    clean watermarks on all internal filenames/paths, add brand text files,
    and repack into a single clean ZIP archive.
    """
    report_progress("processing", 81, "Extracting archive contents...", force=True)
    staging_dir = tempfile.mkdtemp(prefix="pvl_stage_")

    try:
        # Extract using 7z (handles RAR, 7Z, ZIP, TAR, etc. uniformly)
        extracted = False
        try:
            res = subprocess.run(["7z", "x", "-y", f"-o{staging_dir}", source_path],
                                 stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            if res.returncode == 0:
                extracted = True
        except FileNotFoundError:
            pass

        # Fallback to Python zipfile if 7z isn't available and it's a zip
        if not extracted and zipfile.is_zipfile(source_path):
            with zipfile.ZipFile(source_path, "r") as zf:
                zf.extractall(staging_dir)
            extracted = True

        if not extracted:
            raise RuntimeError(f"Could not extract archive {original_name}")

        # Flatten staging directory if there's a single top-level folder
        flatten_staging_dir(staging_dir)

        # Walk through staging dir: remove exclusions and clean watermarks
        report_progress("processing", 83, "Cleaning files and removing exclusions...", force=True)
        stats = filter_and_clean_staging(staging_dir)

        # Add watermark text files at root
        readme_path = os.path.join(staging_dir, "README - Download Info.txt")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(WATERMARK_README)

        brand_path = os.path.join(staging_dir, f"Downloaded from {BRAND_NAME}.txt")
        with open(brand_path, "w", encoding="utf-8") as f:
            f.write(WATERMARK_BRAND)

        # Repack staging dir into output_path (.zip) with ZIP64 & ZIP_STORED
        report_progress("processing", 84, "Packaging clean ZIP...", force=True)
        repack_staging_to_zip(staging_dir, output_path)

        print(f"  Processed archive: {stats['kept']} files kept, {stats['excluded']} excluded, "
              f"{stats['total_size'] // (1024*1024)} MB")
        return stats

    finally:
        shutil.rmtree(staging_dir, ignore_errors=True)


def package_standalone_file(raw_path: str, output_path: str, original_name: str):
    """
    For disk images (.iso) and standalone binaries (.pac, .img, .bin):
    Place the intact file into the container ZIP under its clean unwatermarked name,
    along with the download branding text files.
    """
    report_progress("processing", 82, "Packaging standalone file...", force=True)
    cleaned_inner_name = clean_watermarks(original_name)
    if not cleaned_inner_name:
        cleaned_inner_name = original_name

    CHUNK_SIZE = 64 * 1024 * 1024
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_STORED, allowZip64=True) as out_zip:
        with open(raw_path, "rb") as src, \
             out_zip.open(cleaned_inner_name, "w", force_zip64=True) as dst:
            while True:
                chunk = src.read(CHUNK_SIZE)
                if not chunk:
                    break
                dst.write(chunk)
        out_zip.writestr(f"Downloaded from {BRAND_NAME}.txt", WATERMARK_BRAND)
        out_zip.writestr(f"README - Download Info.txt", WATERMARK_README)
    print(f"  Packaged standalone file: {original_name} -> {cleaned_inner_name}")


# ─────────────────────────────────────────────
#  Hugging Face Upload
# ─────────────────────────────────────────────

def upload_to_hf(file_path: str, hf_filename: str) -> str:
    """Upload a file to the Hugging Face dataset repo. Returns the download URL."""
    report_progress("uploading", 88, "Uploading to permanent cache...", force=True)

    api = HfApi(token=HF_TOKEN)

    # Upload the file
    api.upload_file(
        path_or_fileobj=file_path,
        path_in_repo=hf_filename,
        repo_id=HF_REPO_ID,
        repo_type="dataset",
        commit_message=f"Cache: {hf_filename}",
    )

    # Construct the direct download URL
    hf_url = f"https://huggingface.co/datasets/{HF_REPO_ID}/resolve/main/{hf_filename}"
    print(f"  Uploaded to HF: {hf_url}")
    return hf_url


# ─────────────────────────────────────────────
#  Main Pipeline
# ─────────────────────────────────────────────

def main():
    print("=" * 60)
    print(f"PVL Build Worker")
    print(f"  File ID:   {FILE_ID}")
    print(f"  Filename:  {FILE_NAME}")
    print(f"  Build ID:  {BUILD_ID}")
    print(f"  Excludes:  {EXCLUDE_PATTERNS}")
    print(f"  HF Repo:   {HF_REPO_ID}")
    print("=" * 60)

    work_dir = tempfile.mkdtemp(prefix="pvl_build_")
    raw_path = os.path.join(work_dir, "raw_download")
    processed_path = os.path.join(work_dir, "processed.zip")

    try:
        # ─── Step 1: Get file metadata ───
        is_mediafire = (SOURCE_TYPE == "mediafire") or FILE_ID.startswith("mf_") or ("mediafire.com" in SOURCE_URL)
        original_name = FILE_NAME

        if not is_mediafire:
            report_progress("metadata", 2, "Fetching file info...", force=True)
            try:
                meta = get_file_metadata(FILE_ID)
                meta_name = meta.get("name", "")
                if meta_name and not is_generic_filename(meta_name):
                    original_name = meta_name
                file_size = int(meta.get("size", 0))
                mime_type = meta.get("mimeType", "")
                print(f"  File: {original_name} ({file_size // (1024*1024)} MB, {mime_type})")
            except Exception as e:
                print(f"  Metadata fetch failed (non-fatal): {e}")

        # ─── Step 2: Download from Source ───
        report_progress("downloading", 5, "Starting download...", force=True)

        if not download_file(FILE_ID, raw_path):
            report_error("All download methods failed. File may be restricted or quota fully exhausted.")
            sys.exit(1)

        # Update original_name ONLY if it is currently generic or an ID
        if is_generic_filename(original_name):
            if FILE_NAME and not is_generic_filename(FILE_NAME):
                original_name = FILE_NAME
            elif SOURCE_URL:
                src_parts = [p for p in SOURCE_URL.split("?")[0].split("/") if p and p.lower() not in ("file", "view", "edit", "download")]
                if src_parts and "." in src_parts[-1] and not is_generic_filename(src_parts[-1]):
                    original_name = clean_watermarks(urllib.parse.unquote(src_parts[-1]))
            if is_generic_filename(original_name):
                original_name = f"{FILE_ID}.zip"

        raw_size = os.path.getsize(raw_path)
        report_progress("downloading", 80,
                        f"Download complete ({raw_size // (1024*1024)} MB)", force=True)

        # ─── Step 3: Process the File ───
        if is_extractable_archive(raw_path, original_name):
            stats = process_archive(raw_path, processed_path, original_name)
        else:
            package_standalone_file(raw_path, processed_path, original_name)

        processed_size = os.path.getsize(processed_path)
        report_progress("processing", 85,
                        f"Processing complete ({processed_size // (1024*1024)} MB)", force=True)

        # Sanity check: a ZIP with only watermarks and no real content is ~3-4KB.
        # Any real firmware file produces at least several MB. If we got less than
        # 10KB, the download was garbage and we'd be poisoning the cache.
        if processed_size < 10240:
            report_error(f"Processed ZIP is only {processed_size} bytes — source download was likely corrupt or empty. Aborting.")
            sys.exit(1)

        # ─── Step 4: Build the HF filename ───
        # Format: {fileId}/branded_name.zip
        # First strip third-party site watermarks from the source filename
        cleaned_name = clean_watermarks(original_name)
        base_name = os.path.splitext(cleaned_name)[0]
        # Strip existing branding if present
        for strip in [" - lexzytechinc.com", " — lexzytechinc.com", "- lexzytechinc.com", "— lexzytechinc.com", "lexzytechinc.com"]:
            base_name = base_name.replace(strip, "").strip()
        if is_generic_filename(base_name):
            base_name = FILE_ID
        branded_name = f"{base_name} - {BRAND_NAME}.zip"
        print(f"  Original name: {original_name}")
        print(f"  Cleaned name:  {cleaned_name}")
        print(f"  Branded name:  {branded_name}")
        # HF filename uses fileId prefix for uniqueness
        hf_filename = f"{FILE_ID}/{branded_name}"

        # ─── Step 5: Upload to Hugging Face ───
        hf_url = upload_to_hf(processed_path, hf_filename)

        # ─── Step 6: Report completion ───
        report_complete(hf_url, processed_size)

        print("\n" + "=" * 60)
        print("BUILD SUCCESSFUL")
        print(f"  HF URL: {hf_url}")
        print(f"  Size:   {processed_size // (1024*1024)} MB")
        print("=" * 60)

    except SystemExit:
        raise
    except Exception as e:
        traceback.print_exc()
        report_error(f"Build failed: {str(e)}")
        sys.exit(1)
    finally:
        # Cleanup temp files
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
