#!/usr/bin/env python3
"""
PVL Build Worker — Downloads from Google Drive, processes ZIP, uploads to Hugging Face.

Runs on GitHub Actions. Reads all config from environment variables.
Posts real-time progress updates back to WordPress.

Environment variables (set by GitHub Actions):
  SA_CREDENTIALS_PATH   — Path to Service Account JSON
  GAS_BRIDGE_URL        — Google Apps Script bridge URL
  GAS_BRIDGE_SECRET     — GAS bridge shared secret
  HF_TOKEN              — Hugging Face write token
  HF_REPO_ID            — HF dataset repo (e.g. adminlexzytech/phone-firmware)
  BUILD_CALLBACK_SECRET — Shared secret for progress updates
  FILE_ID               — Google Drive file ID to download
  FILE_NAME             — Original filename
  CALLBACK_URL          — WordPress AJAX URL for progress reports
  BUILD_ID              — Unique build identifier
  EXCLUDE_PATTERNS      — Newline-separated glob patterns to exclude
"""

import os
import sys
import json
import time
import shutil
import hashlib
import zipfile
import fnmatch
import tempfile
import traceback
from pathlib import Path
from datetime import datetime, timezone

import jwt       # PyJWT
import requests
from huggingface_hub import HfApi

# ─────────────────────────────────────────────
#  Configuration
# ─────────────────────────────────────────────

SA_CREDENTIALS_PATH = os.environ["SA_CREDENTIALS_PATH"]
GAS_BRIDGE_URL      = os.environ["GAS_BRIDGE_URL"]
GAS_BRIDGE_SECRET   = os.environ["GAS_BRIDGE_SECRET"]
HF_TOKEN            = os.environ["HF_TOKEN"]
HF_REPO_ID          = os.environ["HF_REPO_ID"]
CALLBACK_SECRET     = os.environ["BUILD_CALLBACK_SECRET"]
FILE_ID             = os.environ["FILE_ID"]
FILE_NAME           = os.environ["FILE_NAME"]
CALLBACK_URL        = os.environ["CALLBACK_URL"]
BUILD_ID            = os.environ["BUILD_ID"]
EXCLUDE_PATTERNS    = [p.strip() for p in os.environ.get("EXCLUDE_PATTERNS", "").split("\n") if p.strip()]

DRIVE_API_BASE   = "https://www.googleapis.com/drive/v3"
DRIVE_UPLOAD_BASE = "https://www.googleapis.com/upload/drive/v3"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"

BRAND_NAME  = "lexzytechinc.com"
BRAND_DOMAIN = "https://lexzytechinc.com"

WATERMARK_BRAND = (
    "╔═══════════════════════════════════════════════════════╗\n"
    "║                                                       ║\n"
    "║          Downloaded from LexzyTechInc.com              ║\n"
    "║                                                       ║\n"
    "║   This file was downloaded by a verified member of     ║\n"
    "║   LexzyTechInc.com. Redistribution without written     ║\n"
    "║   permission is strictly prohibited.                   ║\n"
    "║                                                       ║\n"
    "║   Website:   https://lexzytechinc.com                  ║\n"
    "║   YouTube:   https://youtube.com/@lexzytech             ║\n"
    "║   Telegram:  https://t.me/LexzyTechinc                 ║\n"
    "║   Facebook:  https://facebook.com/LexzyTech            ║\n"
    "║                                                       ║\n"
    "║   Thank you for supporting our platform!               ║\n"
    "║                                                       ║\n"
    "╚═══════════════════════════════════════════════════════╝\n"
)

WATERMARK_README = (
    "================================================================\n"
    "   DOWNLOAD INFORMATION — LexzyTechInc.com\n"
    "================================================================\n\n"
    "This archive was generated by the LexzyTechInc.com\n"
    "download system.\n\n"
    "Source:      LexzyTechInc.com (Members Area)\n"
    "Usage:       Personal use only — do not redistribute\n"
    f"Generated:   {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Need Help?\n"
    "────────────────────────────────────────────────────────\n"
    "  Email:     support@lexzytechinc.com\n"
    "  Website:   https://lexzytechinc.com\n\n"
    "────────────────────────────────────────────────────────\n"
    "  Upgrade to VIP\n"
    "────────────────────────────────────────────────────────\n"
    "  Instant downloads, no daily limits, priority support.\n"
    "  https://lexzytechinc.com/upgrade\n\n"
    "© LexzyTechInc.com — All Rights Reserved\n"
)


# ─────────────────────────────────────────────
#  Watermark Cleaning (ported from core.firmware.php → firmware_clean_filename)
# ─────────────────────────────────────────────

import re as _re

def clean_watermarks(filename: str) -> str:
    """Strip third-party site watermarks from firmware filenames.

    Mirrors the PHP firmware_clean_filename() patterns so files
    uploaded to HF have clean names regardless of source site.
    """
    c = filename

    # [Hovatek], [NaijaROM], [FirmwareFile], [up_addROM.com]_, etc. at start
    c = _re.sub(
        r'^\[(?:Hovatek|NaijaROM|FirmwareFile|XDAFirmware|up_addROM\.com|addROM\.com|'
        r'MobiFirmware|Firmware4mobile|Repairmymobile|FirmwareOS|HardReset\.info|MobileGuru4)\]\s*_?',
        '', c, flags=_re.I)

    # _[HardReset.info] suffix anywhere
    c = _re.sub(r'_?\[HardReset\.info\]', '', c, flags=_re.I)

    # Leading site prefix: up_addROM.com_ or similar (BEFORE standalone replacement)
    c = _re.sub(
        r'^(?:up_)?(?:addROM|TecnoFirmware|NaijaROM|FirmwareFile|MobiFirmware|'
        r'Firmware4mobile|Firmware4mobiles|Repairmymobile|RepairMyMobile|FirmwareOS|'
        r'HardReset|MobileGuru4)\.(?:com|net|org|co|in|info)[_\s-]*',
        '', c, flags=_re.I)

    # _by_(FirmwareOS.com) -- specific pattern BEFORE general parens removal
    c = _re.sub(r'_?by_?\(?FirmwareOS(?:\.com)?\)?', '', c, flags=_re.I)

    # _by_SiteName.Com suffix
    c = _re.sub(r'_by_[a-zA-Z0-9]+\.(?:com|net|org)', '', c, flags=_re.I)

    # Site names in parentheses: (MobiFirmware.com), (by_NaijaROM.Com), (firmwarefile.com), etc.
    c = _re.sub(r'\([^)]*\.(?:com|net|org|io|co|in|info)[^)]*\)', '', c, flags=_re.I)

    # Parenthesized by-watermarks even without .com: _(by_SiteName), _(by_NaijaROM)
    c = _re.sub(r'_?\(by[_\s][^)]*\)', '', c, flags=_re.I)

    # Standalone site name references (non-parenthesized)
    c = _re.sub(
        r'[\s_-]*(?:addROM|TecnoFirmware|NaijaROM|FirmwareFile|MobiFirmware|XDAFirmware|'
        r'Firmware4mobile|Firmware4mobiles|Repairmymobile|RepairMyMobile|FirmwareOS|'
        r'HardReset|MobileGuru4)\.(?:com|net|org|co|in|info)[\s_-]*',
        '_', c, flags=_re.I)

    # _by_AnySiteName before .zip/.rar/.7z/.pac extension
    c = _re.sub(r'_by_[a-zA-Z0-9_]+(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # _Repairmymobile / _ RepairMyMobile.in suffix before extension
    c = _re.sub(r'[\s_-]+Repairmymobile(?:\.(?:co|in))?(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # _RMM suffix (RepairMyMobile abbreviation)
    c = _re.sub(r'_?RMM(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # _Firmware4mobile suffix before extension
    c = _re.sub(r'_?Firmware4mobiles?(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # _MobileGuru4.com / _MobileGuru4 suffix before extension
    c = _re.sub(r'_?MobileGuru4(?:\.com)?(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # Catch-all: trailing _by or _by_ left behind after other removals
    c = _re.sub(r'[_\s-]+by[_\s]*(?=\.(?:zip|rar|7z|pac)$)', '', c, flags=_re.I)

    # Cleanup: double underscores/dashes
    c = _re.sub(r'_{2,}', '_', c)
    c = _re.sub(r'-{2,}', '-', c)

    # Trailing underscore/dash before extension
    c = _re.sub(r'[_-]+\.(?=zip|rar|7z|pac)', '.', c, flags=_re.I)

    # Leading underscore/dash
    c = _re.sub(r'^[_-]+', '', c)

    return c.strip()


# ─────────────────────────────────────────────
#  Progress Reporting
# ─────────────────────────────────────────────

_last_progress_time = 0

def report_progress(stage: str, percent: int, message: str = "", force: bool = False):
    """Post a progress update to WordPress. Throttled to every 15 seconds unless forced."""
    global _last_progress_time
    now = time.time()
    if not force and (now - _last_progress_time) < 15:
        return
    _last_progress_time = now

    print(f"[{percent}%] {stage}: {message}")

    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    stage,
            "percent":  min(percent, 100),
            "message":  message,
        }, timeout=10)
    except Exception as e:
        print(f"  Warning: progress callback failed: {e}")


def report_error(message: str):
    """Report a fatal error to WordPress."""
    print(f"[ERROR] {message}")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "error",
            "percent":  0,
            "message":  message,
        }, timeout=10)
    except Exception:
        pass


def report_complete(hf_url: str, file_size: int):
    """Report successful completion to WordPress."""
    print(f"[100%] Complete: {hf_url} ({file_size} bytes)")
    try:
        requests.post(CALLBACK_URL, json={
            "build_id": BUILD_ID,
            "file_id":  FILE_ID,
            "secret":   CALLBACK_SECRET,
            "stage":    "complete",
            "percent":  100,
            "message":  "Build complete",
            "hf_url":   hf_url,
            "hf_size":  file_size,
        }, timeout=10)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  Google Drive Authentication (Service Account)
# ─────────────────────────────────────────────

_cached_token = None
_token_expiry = 0

def get_access_token() -> str:
    """Get a Google OAuth2 access token using the Service Account."""
    global _cached_token, _token_expiry

    if _cached_token and time.time() < _token_expiry:
        return _cached_token

    with open(SA_CREDENTIALS_PATH, "r") as f:
        creds = json.load(f)

    now = int(time.time())
    payload = {
        "iss":   creds["client_email"],
        "scope": "https://www.googleapis.com/auth/drive",
        "aud":   GOOGLE_TOKEN_URL,
        "iat":   now,
        "exp":   now + 3600,
    }

    token = jwt.encode(payload, creds["private_key"], algorithm="RS256")
    resp = requests.post(GOOGLE_TOKEN_URL, data={
        "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "assertion":  token,
    }, timeout=30)
    resp.raise_for_status()
    data = resp.json()

    _cached_token = data["access_token"]
    _token_expiry = now + data.get("expires_in", 3600) - 60
    return _cached_token


# ─────────────────────────────────────────────
#  Google Drive File Metadata
# ─────────────────────────────────────────────

def get_file_metadata(file_id: str) -> dict:
    """Fetch file metadata from Google Drive."""
    token = get_access_token()
    resp = requests.get(f"{DRIVE_API_BASE}/files/{file_id}", params={
        "fields": "id,name,mimeType,size",
        "supportsAllDrives": "true",
    }, headers={"Authorization": f"Bearer {token}"}, timeout=30)
    resp.raise_for_status()
    return resp.json()


# ─────────────────────────────────────────────
#  Download Cascade (mirrors PHP pvl_sa_download_to_temp)
# ─────────────────────────────────────────────

def download_file(file_id: str, dest_path: str) -> bool:
    """
    Download a file from Google Drive using the same cascade as the PHP engine:
      1. GAS Bridge copy
      2. GAS Bridge folder + signed URL
      3. Web download URL with SA Bearer token
      4. Standard Drive API download
    """
    # ─── Approach 1A: GAS Copy ───
    report_progress("downloading", 5, "Trying GAS copy...", force=True)
    if gas_try_copy(file_id, dest_path):
        return True

    # ─── Approach 1B: GAS Folder + Signed URL ───
    report_progress("downloading", 10, "Trying GAS folder download...")
    if gas_try_folder_download(file_id, dest_path):
        return True

    # ─── Approach 2: Web download URL ───
    report_progress("downloading", 15, "Trying web download URL...")
    if web_download(file_id, dest_path):
        return True

    # ─── Approach 3: Standard API ───
    report_progress("downloading", 20, "Trying API download...")
    if api_download(file_id, dest_path):
        return True

    return False


def gas_try_copy(file_id: str, dest_path: str) -> bool:
    """GAS Approach A: Server-side copy with fresh quota."""
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action": "copy",
            "fileId": file_id,
            "secret": GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        if not data.get("success"):
            print(f"  GAS copy failed: {data.get('error', 'unknown')}")
            return False

        copy_id = data["copyId"]
        download_url = data["downloadUrl"]
        print(f"  GAS copy created: {copy_id}")

        # Download the copy
        success = stream_download(download_url, dest_path, auth=None)

        # Cleanup the copy
        try:
            requests.get(GAS_BRIDGE_URL, params={
                "action": "cleanup",
                "copyId": copy_id,
                "secret": GAS_BRIDGE_SECRET,
            }, timeout=30)
        except Exception:
            pass

        return success

    except Exception as e:
        print(f"  GAS copy error: {e}")
        return False


def gas_try_folder_download(file_id: str, dest_path: str) -> bool:
    """GAS Approach B: Folder + shortcut + signed URL."""
    try:
        resp = requests.get(GAS_BRIDGE_URL, params={
            "action":   "folder_download",
            "fileId":   file_id,
            "fileName": FILE_NAME,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=120)
        data = resp.json()

        if not data.get("success"):
            print(f"  GAS folder failed: {data.get('error', 'unknown')}")
            return False

        folder_id  = data["folderId"]
        signed_url = data["signedUrl"]
        print(f"  GAS folder created: {folder_id}, got signed URL")

        # Download the folder ZIP
        zip_path = dest_path + ".folder.zip"
        if not stream_download(signed_url, zip_path, auth=None):
            cleanup_gas_folder(folder_id)
            return False

        # Extract target file from the folder ZIP
        success = extract_from_google_zip(zip_path, dest_path)
        os.unlink(zip_path)
        cleanup_gas_folder(folder_id)
        return success

    except Exception as e:
        print(f"  GAS folder error: {e}")
        return False


def web_download(file_id: str, dest_path: str) -> bool:
    """Approach 2: Web download URL with SA Bearer token."""
    try:
        token = get_access_token()
        url = f"https://drive.usercontent.google.com/download?id={file_id}&export=download&confirm=t"
        return stream_download(url, dest_path, auth=f"Bearer {token}")
    except Exception as e:
        print(f"  Web download error: {e}")
        return False


def api_download(file_id: str, dest_path: str) -> bool:
    """Approach 3: Standard Google Drive API download."""
    try:
        token = get_access_token()
        url = f"{DRIVE_API_BASE}/files/{file_id}"
        return stream_download(url, dest_path, auth=f"Bearer {token}",
                               params={"alt": "media", "supportsAllDrives": "true"})
    except Exception as e:
        print(f"  API download error: {e}")
        return False


def stream_download(url: str, dest_path: str, auth: str = None, params: dict = None) -> bool:
    """Stream a URL to a local file. Reports progress during download."""
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
    if auth:
        headers["Authorization"] = auth

    resp = requests.get(url, headers=headers, params=params, stream=True, timeout=30, allow_redirects=True)

    # Reject obvious HTML error pages (Google returns 200 + text/html for quota errors)
    content_type = resp.headers.get("Content-Type", "")
    if "text/html" in content_type:
        snippet = resp.content[:500].decode("utf-8", errors="replace")
        print(f"  Download returned HTML: {snippet[:200]}")
        return False

    total = int(resp.headers.get("Content-Length", 0))
    downloaded = 0

    with open(dest_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=65536):
            f.write(chunk)
            downloaded += len(chunk)
            if total > 0:
                pct = int((downloaded / total) * 60) + 20  # 20-80% range
                report_progress("downloading", pct,
                                f"Downloaded {downloaded // (1024*1024)} / {total // (1024*1024)} MB")

    size = os.path.getsize(dest_path)

    # Check if it's actually HTML despite the Content-Type header lying
    with open(dest_path, "rb") as f:
        head = f.read(256)
    if b"<!DOCTYPE" in head or b"<html" in head or b"Quota exceeded" in head:
        snippet = head[:200].decode("utf-8", errors="replace")
        print(f"  Download is HTML despite Content-Type ({content_type}): {snippet[:150]}")
        os.unlink(dest_path)
        return False

    # Reject suspiciously small files (any real firmware ZIP is at least several MB)
    if size < 1024:
        print(f"  Download too small: {size} bytes (expected a real file, not an error page)")
        os.unlink(dest_path)
        return False

    print(f"  Downloaded {size:,} bytes")
    return True


def extract_from_google_zip(zip_path: str, dest_path: str) -> bool:
    """Extract the largest non-directory file from a Google folder ZIP."""
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            target = None
            target_size = 0
            for info in zf.infolist():
                if info.is_dir() or info.filename.startswith("."):
                    continue
                if info.file_size > target_size:
                    target = info
                    target_size = info.file_size

            if not target:
                print("  No files found in folder ZIP")
                return False

            with zf.open(target) as src, open(dest_path, "wb") as dst:
                shutil.copyfileobj(src, dst)

            print(f"  Extracted: {target.filename} ({target_size:,} bytes)")
            return True
    except Exception as e:
        print(f"  ZIP extraction error: {e}")
        return False


def cleanup_gas_folder(folder_id: str):
    """Delete a GAS temp folder."""
    try:
        requests.get(GAS_BRIDGE_URL, params={
            "action":   "cleanup_folder",
            "folderId": folder_id,
            "secret":   GAS_BRIDGE_SECRET,
        }, timeout=30)
    except Exception:
        pass


# ─────────────────────────────────────────────
#  ZIP Processing (flatten + filter + watermark)
# ─────────────────────────────────────────────

def should_exclude(entry_name: str) -> bool:
    """Check if a ZIP entry matches any exclude pattern."""
    basename = os.path.basename(entry_name)
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(basename, pattern) or fnmatch.fnmatch(entry_name, pattern):
            return True
    return False


def process_zip(source_path: str, output_path: str) -> dict:
    """
    Open the source ZIP and create a new output ZIP with:
    - Entries flattened (strip the top-level folder if there's only one)
    - Excluded patterns removed
    - Watermark files added at the root level

    Returns stats dict: {kept, excluded, watermarks, total_size}
    """
    report_progress("processing", 82, "Processing ZIP contents...", force=True)

    stats = {"kept": 0, "excluded": 0, "watermarks": 2, "total_size": 0}

    with zipfile.ZipFile(source_path, "r") as src_zip:
        entries = [e for e in src_zip.infolist() if not e.is_dir()]

        # Detect common top-level folder prefix (for flattening)
        prefix = detect_common_prefix(entries)

        CHUNK_SIZE = 64 * 1024 * 1024  # 64MB — memory stays flat regardless of entry size

        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_STORED, allowZip64=True) as out_zip:
            for entry in entries:
                name = entry.filename

                # Strip the common prefix to flatten
                if prefix and name.startswith(prefix):
                    flat_name = name[len(prefix):]
                else:
                    flat_name = name

                if not flat_name or flat_name.endswith("/"):
                    continue

                # Check exclusion
                if should_exclude(flat_name):
                    stats["excluded"] += 1
                    print(f"  Excluded: {flat_name}")
                    continue

                # Stream entry to output in chunks — never buffers full file
                with src_zip.open(entry, "r") as src, \
                     out_zip.open(flat_name, "w", force_zip64=True) as dst:
                    while True:
                        chunk = src.read(CHUNK_SIZE)
                        if not chunk:
                            break
                        dst.write(chunk)

                stats["kept"] += 1
                stats["total_size"] += entry.file_size

            # Add watermark files at root
            out_zip.writestr(f"Downloaded from {BRAND_NAME}.txt", WATERMARK_BRAND)
            out_zip.writestr(f"README - Download Info.txt", WATERMARK_README)

    print(f"  Processed: {stats['kept']} kept, {stats['excluded']} excluded, "
          f"{stats['total_size'] // (1024*1024)} MB")
    return stats


def detect_common_prefix(entries: list) -> str:
    """
    If all entries share a single top-level folder, return it as a prefix
    so we can strip it (flatten the ZIP).
    e.g. all start with 'Tecno_Pova_8_5G_.../'' → return that prefix
    """
    if not entries:
        return ""

    # Get first path component of each entry
    tops = set()
    for e in entries:
        parts = e.filename.split("/")
        if len(parts) > 1:
            tops.add(parts[0])
        else:
            return ""  # File at root level — no common prefix

    if len(tops) == 1:
        prefix = tops.pop() + "/"
        print(f"  Flattening: stripping common prefix '{prefix}'")
        return prefix

    return ""


# ─────────────────────────────────────────────
#  Hugging Face Upload
# ─────────────────────────────────────────────

def upload_to_hf(file_path: str, hf_filename: str) -> str:
    """Upload a file to the Hugging Face dataset repo. Returns the download URL."""
    report_progress("uploading", 88, "Uploading to permanent cache...", force=True)

    api = HfApi(token=HF_TOKEN)

    # Upload the file
    api.upload_file(
        path_or_fileobj=file_path,
        path_in_repo=hf_filename,
        repo_id=HF_REPO_ID,
        repo_type="dataset",
        commit_message=f"Cache: {hf_filename}",
    )

    # Construct the direct download URL
    hf_url = f"https://huggingface.co/datasets/{HF_REPO_ID}/resolve/main/{hf_filename}"
    print(f"  Uploaded to HF: {hf_url}")
    return hf_url


# ─────────────────────────────────────────────
#  Main Pipeline
# ─────────────────────────────────────────────

def main():
    print("=" * 60)
    print(f"PVL Build Worker")
    print(f"  File ID:   {FILE_ID}")
    print(f"  Filename:  {FILE_NAME}")
    print(f"  Build ID:  {BUILD_ID}")
    print(f"  Excludes:  {EXCLUDE_PATTERNS}")
    print(f"  HF Repo:   {HF_REPO_ID}")
    print("=" * 60)

    work_dir = tempfile.mkdtemp(prefix="pvl_build_")
    raw_path = os.path.join(work_dir, "raw_download")
    processed_path = os.path.join(work_dir, "processed.zip")

    try:
        # ─── Step 1: Get file metadata ───
        report_progress("metadata", 2, "Fetching file info...", force=True)
        try:
            meta = get_file_metadata(FILE_ID)
            original_name = meta.get("name", FILE_NAME)
            file_size = int(meta.get("size", 0))
            mime_type = meta.get("mimeType", "")
            print(f"  File: {original_name} ({file_size // (1024*1024)} MB, {mime_type})")
        except Exception as e:
            print(f"  Metadata fetch failed (non-fatal): {e}")
            original_name = FILE_NAME
            file_size = 0
            mime_type = ""

        # ─── Step 2: Download from Google Drive ───
        report_progress("downloading", 5, "Starting download...", force=True)

        if not download_file(FILE_ID, raw_path):
            report_error("All download methods failed. File may be restricted or quota fully exhausted.")
            sys.exit(1)

        raw_size = os.path.getsize(raw_path)
        report_progress("downloading", 80,
                        f"Download complete ({raw_size // (1024*1024)} MB)", force=True)

        # ─── Step 3: Process the ZIP ───
        # Check if the downloaded file is actually a ZIP
        is_zip = False
        try:
            with zipfile.ZipFile(raw_path, "r") as test:
                is_zip = True
        except zipfile.BadZipFile:
            is_zip = False

        if is_zip and (EXCLUDE_PATTERNS or True):
            # Process: flatten, filter, watermark
            stats = process_zip(raw_path, processed_path)
        else:
            # Not a ZIP (or no processing needed) — wrap in a new ZIP with watermarks
            report_progress("processing", 82, "Packaging file...", force=True)
            with zipfile.ZipFile(processed_path, "w", zipfile.ZIP_STORED) as out_zip:
                # Add the raw file
                out_zip.write(raw_path, original_name)
                # Add watermarks
                out_zip.writestr(f"Downloaded from {BRAND_NAME}.txt", WATERMARK_BRAND)
                out_zip.writestr(f"README - Download Info.txt", WATERMARK_README)

        processed_size = os.path.getsize(processed_path)
        report_progress("processing", 85,
                        f"Processing complete ({processed_size // (1024*1024)} MB)", force=True)

        # Sanity check: a ZIP with only watermarks and no real content is ~3-4KB.
        # Any real firmware file produces at least several MB. If we got less than
        # 10KB, the download was garbage and we'd be poisoning the cache.
        if processed_size < 10240:
            report_error(f"Processed ZIP is only {processed_size} bytes — source download was likely corrupt or empty. Aborting.")
            sys.exit(1)

        # ─── Step 4: Build the HF filename ───
        # Format: {fileId}/branded_name.zip
        # First strip third-party site watermarks from the source filename
        cleaned_name = clean_watermarks(original_name)
        base_name = os.path.splitext(cleaned_name)[0]
        # Strip existing branding if present
        for strip in [" - lexzytechinc.com", "- lexzytechinc.com", "lexzytechinc.com"]:
            base_name = base_name.replace(strip, "").strip()
        branded_name = f"{base_name} - {BRAND_NAME}.zip"
        print(f"  Original name: {original_name}")
        print(f"  Cleaned name:  {cleaned_name}")
        print(f"  Branded name:  {branded_name}")
        # HF filename uses fileId prefix for uniqueness
        hf_filename = f"{FILE_ID}/{branded_name}"

        # ─── Step 5: Upload to Hugging Face ───
        hf_url = upload_to_hf(processed_path, hf_filename)

        # ─── Step 6: Report completion ───
        report_complete(hf_url, processed_size)

        print("\n" + "=" * 60)
        print("BUILD SUCCESSFUL")
        print(f"  HF URL: {hf_url}")
        print(f"  Size:   {processed_size // (1024*1024)} MB")
        print("=" * 60)

    except SystemExit:
        raise
    except Exception as e:
        traceback.print_exc()
        report_error(f"Build failed: {str(e)}")
        sys.exit(1)
    finally:
        # Cleanup temp files
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
